-- 任务详情补译（locales_quest）—— 游戏中仍可接取、且仍是英文的任务
--
-- 与 locales_quest_objectives.sql / locales_quest_rewards.sql 同一套筛选条件。
-- 只写 Details_loc4 列。这是四个文件里最大的一块（748 条，约 45 万字符），分批提交。
--
-- 同一段英文在多个任务上重复出现时共用同一条译文（按文本去重后 561 条覆盖 748 个任务）。
-- $B/$b 换行、$N/$n/$C/$R 等占位符一律保留原样。
--
-- 生效：mangosd 控制台执行 `.reload locales_quest`

SET NAMES utf8mb4;


-- ---- 第 1 批：55 条任务 ----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (4105, '精灵的同胞也在困扰着我，兄弟。我的部族，我自己的族人，被那邪恶、极其邪恶的巫毒夺去了神智。有一天，Loa 在梦中去寻我们的代言人，要他们制作强大的魔精——梦境魔精。$B$B如此强大的魔精需要受巨龙祝福过的圣水。于是我寻到了那座绿色巨门，在那里我找到了恶魔，并用他们的血弄脏了自己的手，而代言人却逃走了！等我回到家中，我的族人却以敌意待我，把我赶走了。他们说，我不再是影剥者的一员。$B$B邪恶的巫毒夺走了他们的神智，兄弟。但要破除邪恶的巫毒，你需要付出鲜血与良善的魔精。这两样代价都可以在祖尔哈塔偿付。你会在那里找到带着梦境魔精的代言人甘霍塔。不远处你会找到督军汉森托，他的血正是你需要的。他是这一切蠢行的根源，而那正是拨乱反正的正途！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- There be something other than demons on my mind, mon. My tribe, my own people. Lost to the
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7002, '有些士兵正忙着为马厩管理员捕捉狼，另一些人则要备齐骑乘所需的简单装备——我说的自然是坐骑挽具。$B$B你必须去猎杀本地的山羊，正是雷矛骑兵用作坐骑的那种山羊！$B$B杀掉它们，把皮交给我。等我们把皮凑齐，就能为骑兵缝制挽具。霜狼狼骑兵将再度驰骋！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- While some of our soldiers are busy capturing wolves for the stable master, others must pr
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7385, '你也可以一次献上更多从敌人身上取来的鲜血。一整加仑的分量，我乐意收下，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You have the option of offering larger quantities of the blood taken from our enemies. I w
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7386, '有时你会连续数日甚至数周陷于战斗之中。在这样漫长的征战里，你可能积攒下大批的霜狼风暴水晶。$B$B议会收下这样的献礼，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- There are times which you may be entrenched in battle for days or weeks on end. During tho
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7813, '和大多数布料一样，我们的羊毛储备已经见底。目前库存的状况是，我们只需要你提供总计六十块羊毛；有了其他人的支持，我们应当能够达成目标。$B$B顺带一提，像羊毛这样慷慨的馈赠，必定能提升你在当地的声望！如果你身上正好带着六十块羊毛布，并愿意捐献出来，我现在就可以收下。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- As with most other fabrics, our stocks of wool are at an all-time low. Our stores are such
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8184, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8185, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8186, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8187, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8188, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8189, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8190, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8191, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8192, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8195, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8238, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8239, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8271, '本地的冰斧巨魔是残忍的野人，他们最乐意的事莫过于把我们的骨头丢进那锅恶心的炖菜里。$B$B我们必须让他们见识我们的力量！$B$B我们从他们的洞窟里找回了记载其首领层级的典籍。这些古物显示，他们的首领「血怒者科尔拉克」惯于隐藏自己，直到有了现身的理由。$B$B科尔拉克死，冰斧部族便亡！杀了他再回来。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The indigenous Winterax trolls of the region are ruthless savages that would love nothing 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8272, '入侵的雷矛并非此地唯一的威胁，士兵。山谷中的战争在两条战线上进行。食人的冰斧巨魔同样在争夺权力。$B$B他们的首领是「血怒者科尔拉克」——一头残忍而狡诈的野兽。$B$B对科尔拉克的一击，可能就是击垮冰斧部族的沉重打击。杀掉那畜生，你会得到奖赏！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The invading Stormpike are not the only threat in the region, soldier. The war in the Vall
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8383, '奥特兰克山谷的战斗仍在继续，$N！近来你可尽了自己的一份力，$N？') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Battle in Alterac Valley rages on, $N! Have you done your part as of late, $N?
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8384, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8385, '啊，$N。我希望你继续把经验带到各个战场上去。我们许多前线的将士都敬仰你这样久经沙场的老兵。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Ah, $N. I hope you continue to lend your experience to the different battlefronts. A lot o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8386, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8387, '奥特兰克的战斗仍在继续！你必须重返奥特兰克山谷，再次把入侵者逐出霜狼的领地，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle for Alterac rages on! You must return to Alterac Valley and once more drive the
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8388, '许多勇敢的战士都仰望着你，$N。在与联盟的战斗中，你始终是众人的榜样。你此番远行带来了什么消息？') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Many brave fighters look up to you, $N. You continue to be an example for all in the fight
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8389, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8391, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8392, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8397, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8398, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8404, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8405, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8406, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8407, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8408, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8431, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8432, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8433, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8434, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8435, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8440, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8441, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8442, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8443, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8595, '我看得出，你不是普通的凡人，$n。你对抗上古之神的胜算虽然微乎其微，却比我们此刻要大。毕竟，他防着龙族登门，却没料到会遇上你这样的人。$b$b正如阿纳克洛斯与鹿盔在千年前以凡人与龙族的联手击败了其拉虫人，我们也来立下盟约。赢得青铜龙军团的信任，你便赢得我们的信任。到那时，我们才会把你塑造成真正的勇士。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I see that youre no ordinary mortal, $n. Your chances against the Old God, however infinit
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8608, '你回来了？有意思。如你所见，我仍在为安其拉之战募集物资。也就是说，我还得请你再出去一趟，替我收集一捆魔纹绷带。期待你归来，$C。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You returned? Interesting. As you can see I am still collecting for the AhnQiraj war effor
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8751, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8756, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8761, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (9142, '规矩你懂，小子。一枚英勇徽记换一份工匠的委任状。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You know the drill, kid. One valor token gets you a craftsmans writ.
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (39980, '什么样扭曲的心智才会去袭击平民？这场冲突中已有无数无辜者丧命，但有些人却专门以伤害无力自保者为乐。不只是男人，还有女人和孩子。这样的暴行不能不予回应。我们必须出手阻止。找出过去一天内不义击杀数最多的玩家，终结他们的屠戮。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- What kind of deranged mind attacks civilians? Countless innocents have died in this confli
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (39981, '大屠杀有什么荣耀可言？没有，那是疯狂，而我们有责任阻止它。要阻止联盟与部落之间的战争吞噬我们所有人，就必须除掉那些最热衷于此的人。找出过去一天内荣耀击杀数最多的玩家，终结他们的嗜血。唯有如此，才能有和平。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- What is honorable about mass slaughter? Nothing, it is madness, and we have a duty to prev
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (40739, '那么，又来换一根巨型香蕉了，是吧？我懂：那味道实在太惊艳，我自己也吃不够！$B$B我只需要你带来三根熟透的特尔阿比姆香蕉和一份梦境之尘。材料一到，我就能再为你转化三根大香蕉。没错，就这么简单！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- So then, back for another Gargantuan Banana, are you? I know: The flavor is so spectacular
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (40740, '我改良了转化工艺，甚至扩建了实验室！一次造出多根巨型香蕉如今完全可能。当然，我需要的还是启动流程所需的材料。$B$B要造十五根巨型香蕉，我需要十五根熟透的特尔阿比姆香蕉，以及五份梦境之尘。若你想要一捆那种巨型香蕉，就把材料带来，我让你美梦成真！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I have refined my transmutation process and even expanded my lab! The ability to create mu
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41274, '你能感受到吗，$C？那弥漫在空气中的爱与倾慕的芬芳？那些热恋中的鸟儿彼此分享的喜悦与迷恋？见证爱在艾泽拉斯蔓延的奇迹，没有什么比这更让我心跳加速了！$B$B你的眼睛出卖了你的心，我读你就像读一本摊开的书。我能看出你渴望了解更多，甚至亲身去体验这份情感。爱有千般形态，并不总如人所想的那么分明。就连我这位爱的传令官，也常为我的箭所选中、蒙受爱的祝福之人感到意外！爱，真是个谜！$B$B不必再找别的证明——只看过去被我的箭射中过的那些人就够了。给我带来一份他们那份独特的爱与倾慕的信物，把这些纪念品带到任意主城交还给我。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Can you feel it, $C? The sweet fragrance of love and admiration that permeates the air? Th

-- ---- 第 2 批：16 条任务（珠宝加工师成长线 41275-41290）----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41275, '$N！你有空吗？你的珠宝加工手艺出类拔萃——我门下少有弟子仅凭我的教导就能达到这样的水准。不用大师也看得出：你天生就该把这门手艺磨炼到极致。$B$B虽说你已远远超出我的期望，可惜我能教的也仅止于此了。但这并不意味着你旅程的终点。还有比我更能胜任的导师，其中一位正是我的好友。也许你已与他相识——他有些多疑、爱抱怨，但只要稍加帮助，他就会倾囊相授。$B$B若你想专精此道、成为珠宝加工大师，就去秘法区找塔瓦斯德·基瑟尔吧。他的指点将为你在这行铺就前路。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N! Do you have a moment? Your skills in jewelcrafting are exceptional, rarely any of my p
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41276, '$N，再次见到你真是太好了。我注意到了——你自然也注意到了——你在这门手艺上的进步堪称飞跃！说真的，我已许久没见过如此天赋异禀的双手。可惜这也意味着我的教导到此为止了。不过你求知的热切显而易见；好在我还能最后帮你一次。$B$B若你想在珠宝加工上更进一步，就去卡加斯找我的好友加卡尔。险恶的荒芜之地不是我这种尸体该待的地方，但像他那样结实的巨魔，再恶劣的环境也应付得来。去找他的路上务必小心，愿你一路平安。$B$B<古尔迈尔短促而诚挚地鞠了一躬。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N, what a splendid sight to have you here with me once more. I have noticed - and you sur
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41277, '$N！你有空吗？你的珠宝加工手艺出类拔萃——我门下少有弟子仅凭我的教导就能达到这样的水准。不用大师也看得出：你天生就该把这门手艺磨炼到极致。$B$B虽说你已远远超出我的期望，可惜我能教的也仅止于此了。但别灰心——我自己的师父瑟格伦，或许能在我不及之处助你一臂之力。$B$B若你想专精此道、成为宝石切割大师——那门操控宝石以增益自身本领的技艺——就去找瑟格伦。他属于一个比我们现今任何文明都更古老的团体，却选择了隐士的生活，独居于荒芜之地的荒野。去古城科尔桑的废墟附近寻他。他不与任何人交谈，但若你把这块水晶拿给他看，我向你保证——他会听你说明来意。路上务必小心，去那片荒凉之地的旅途十分凶险！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N! Do you have a moment? Your skills in jewelcrafting are exceptional, rarely any of my p
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41278, '$N，再次见到你真是太好了。我注意到了——你自然也注意到了——你在这门手艺上的进步堪称飞跃！说真的，我已许久没见过如此天赋异禀的双手。可惜这也意味着我的教导到此为止了。不过你求知的热切显而易见；好在我还能最后帮你一次。$B$B若你想在宝石学上更进一步，有个人或许能助你达成志向——一个神秘莫测的人。他比我所知的一切都更古老，属于一个曾掌控艾泽拉斯矿物知识的古老团体。因此他极重隐私，也就是说，他多半不会与你交谈。来，带上这块水晶。它是我曾在他门下受教的凭证，也能让他知道你可以信任。路上务必小心，愿你一路平安。$B$B<古尔迈尔短促而诚挚地鞠了一躬。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N, what a splendid sight to have you here with me once more. I have noticed - and you sur
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41279, '<你猜想，那该算是这位土灵脸上的笑容。从巨人身上取下的粗糙宝石，在他宽大的手掌里显得很小。他只点了点头，便示意你再次跪下。$B$B当他的手掌再度按上你时，眼前的景象清晰了许多，尽管这过程仍令你吃力。三颗宝石浮现在你内心的视野中。幸好你认得它们：一颗烬石、一颗星红宝石、一颗黄水晶。接着，你看到这三颗宝石被切磨成一种你从未见过的刻面。你凝神细看，把那些动作一一记下。这份智慧已深植你心。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <You assume what you are seeing is a smile on the Earthens face. The rough gemstone from t
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41280, '<视野恢复时，瑟格伦正摆弄着双手之间的什么东西。凑近一看，他毫不费力地把一颗星红宝石切成了你方才见过的刻面。他把宝石放到桌上时，手中又可见另一颗宝石——一颗黄水晶。他重复了同样的过程——接着又用烬石做了一遍。$B$B手艺人用生硬的目光指指你，指指他的作品，然后摊开空着的手掌。你琢磨片刻，终于明白他的意思：他要你把刚学会的三种切割各做五遍。$B$B应该不太难，对吧？>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Regaining your vision, Thegren is tinkering with something between his hands. Upon closer
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41281, '<不必他示意，你便跪下，接受新师父教诲的下一幕幻象。$B$B洁白的厅堂、无尽的瀑布，一股暖意充满你的脑海。在遥远的西方，卡利姆多大陆上，凄凉之地的山峦深处，正是这幻象的源头。曾是圣地的玛拉顿洞窟中，藏着你下一个目标：又一个巨人，这一回是纯净大理石之躯。你需要取回他石身上的一块石板。$B$B你重新站起，向瑟格伦点头，他只是以拳捶胸，便又埋头于自己的工作。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Without having to gesture anything, you kneel down to receive the next vision of your new
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41282, '<瑟格伦面前的桌上摆着三样东西：你从波尔加斯特身上取下的命脉宝石、兰斯利德的大理石纹石肤，以及一块似乎不受岁月侵蚀的精致布料。你仔细端详了许久，转向瑟格伦——他只是面无表情地看着你，不过他那张石雕般的脸本来也看不出什么。$B$B看来这是你最后的考验。用你学到的宝石切割本领，把这颗灼热的石头切磨成完美的形状。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <On the table before Thegren are three things layed out. The Lifeblood Gem you took from B
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41283, '好吧，听我说，我就跟你实话实说。我教你那些秘传工艺，绝不是因为我乐善好施。我向你保证，绝对不是。相反，你要帮我……补充库存，作为交换，你会得到关于我金饰加工的一小份真传。行不行？就这么定了。$B$B请尽快把下面这些东西给我带来，我可不是那种愿意久等的人。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Alright, listen, let me be honest with you. I will not teach you my secret crafting techni
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41284, '信不信由你，住在山底下并不代表你的库里就有源源不断的宝石。而且要是有些子虚乌有的谣言让你没法在这儿做正当生意，那更是雪上加霜。要是我还在诺莫瑞根，这些事都会容易得多，相信我。可话说回来，宝石是珠宝加工的命根子——没有宝石，就没有珠宝，没有买卖，没有钱，付不起房租。你懂的。眼下我急需讨房东欢心，所以需要不少那种闪闪发亮的小宝贝来弥补损失。$B$B我们想到一块去了吧？当然。把下面这些宝石给我带够，我会分你点小东西。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Believe it or not, but living under a mountain does not guarantee you a steady flow of gem
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41285, '不管别人跟你说了我什么——全是谎话！我百分之百、从来没有给任何人做过什么受诅咒的东西。我对手艺有操守，也立过誓！别问我跟谁立的誓。绝对保密。而且绝对、绝对不心虚。$B$B话说回来，似乎某个倒霉冒险者的厄运现在落到我头上了，又一次往我名声上泼脏水。有个大胆的法师找上门来，要一条能增强法术的项链，好去北方那座新近重新发现的吉尔尼斯城探险。我当然照办，给他做了一条——反正房租到期了。可他在那鬼地方的探险，结局嘛……对他算不上好。糟糕的是，他那帮冒险者同伴现在把他的死算在我头上，在铁炉堡到处说我在项链上附了邪咒！$B$B$N，我要你亲自闯一趟吉尔尼斯城，把那条项链给我带回来！我最不愿看到的，就是有人拿它当假证据来对付我。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Whatever youve been told about me - its all lies! I one hundred percent NEVER made any sor
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41286, '到此为止了，好心的旅人。我能教的，你在别处也差不多都能学到。不过，若你求知的渴望不肯就此打住，那我就告诉你我这些巧妙本事的来处。$B$B按理说这话我不该说，但你帮了我的大忙，我不能让你空手而去。向西去，在凄凉之地那片险恶的平原上，你会找到我自己的师父，他离群索居。虽说他喜欢清静，但我知道他不介意有人作伴。若他一开始不搭理你，别泄气——对于那些想求知识的人，他最看重的正是执着！$B$B去找一座俯瞰大海的高塔，那是我最后一次见到他的地方。既然话都说到这儿了，你最好快点走，免得我房东以为我在搞黑市买卖！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- This is it, good traveler. There isnt much more I could teach that you couldnt learn elsew
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41287, '老实跟你说，在这荒野里，我们的物资并不充裕，没法正经教你。我可不像奥格瑞玛那些矮个子绿皮朋友那样资源无限。不过，这难不倒我们。幸运的是，这片土地自然资源丰富，你可以把它们变成上课要用的材料。$B$B就当是一次测验，看看你到底有多少本事。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I will be honest with you, out here in the wilderness, our supplies are not as plentiful a
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41288, '你自然知道，宝石、贵重石料与矿物是珠宝加工的根本。没有它们，做出时髦的饰品固然还是可能的——但说实话，那还有什么意义？依我之见，一颗精致的宝石，甚至一颗华丽雕琢的宝石，才是赋予首饰目的与意义的关键。$B$B给我带来足够多的艾泽拉斯宝石，我们好一起分析它们的特性。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Like youll surely know, gems, valuable stones and minerals are essential to jewelcrafting.
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41289, '我族在金银加工与镶嵌点缀方面有着悠久的历史，无论是可拆卸的还是永久的。我固然会与你分享古老的赞达拉金饰加工传统，但把眼界扩展到其他知识来源同样重要。$B$B我要你去钻研的，是人类制作仪饰章的做法。向北去，离我们那些被遗忘者盟友的领地不远处，你会找到吉尔尼斯这个国家。据说它是旧时代的遗存，如今刚刚向那些勇于挑战其凶险之人敞开。在它那山脊般的高塔之上，便是吉尔尼斯城——据旅行的冒险者说，那是个商业、贸易与庆典之地。$B$B你会在那里找到一份适合我们分析的东西。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- My people have an extensive history about goldsmithing and bedazzlements, be it removable 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41290, '好心的旅人，谢谢你让我能重拾这门许久无法施展的手艺。我曾立誓要继续磨炼技艺，可这些年为部落效力，让我再也无法顾及这个誓约。不过，若像你这样的冒险者再多来几位，或许我终究还能做到。$B$B为了答谢你及时的帮助，让我好好报答你——告诉你我是在哪里练就金饰加工本领的。向西去，在凄凉之地那片险恶的平原上，你会找到我自己的师父，他离群索居。虽说他喜欢清静，但我知道他不介意有人作伴。若他一开始不搭理你，别泄气——对于那些想求知识的人，他最看重的正是执着！$B$B去找一座俯瞰大海的高塔，那是我最后一次见到他的地方。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Good traveler, thank you for letting me practice this craft I had long been unable to. I h
