-- 任务详情补译（locales_quest）—— 游戏中仍可接取、且仍是英文的任务
--
-- 与 locales_quest_objectives.sql / locales_quest_rewards.sql 同一套筛选条件。
-- 只写 Details_loc4 列。这是四个文件里最大的一块（748 条，约 45 万字符），分批提交。
--
-- 同一段英文在多个任务上重复出现时共用同一条译文（按文本去重后 561 条覆盖 748 个任务）。
-- $B/$b 换行、$N/$n/$C/$R 等占位符一律保留原样。
--
-- 生效：mangosd 控制台执行 `.reload locales_quest`

SET NAMES utf8mb4;


-- ---- 第 1 批：55 条任务 ----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (4105, '精灵的同胞也在困扰着我，兄弟。我的部族，我自己的族人，被那邪恶、极其邪恶的巫毒夺去了神智。有一天，Loa 在梦中去寻我们的代言人，要他们制作强大的魔精——梦境魔精。$B$B如此强大的魔精需要受巨龙祝福过的圣水。于是我寻到了那座绿色巨门，在那里我找到了恶魔，并用他们的血弄脏了自己的手，而代言人却逃走了！等我回到家中，我的族人却以敌意待我，把我赶走了。他们说，我不再是影剥者的一员。$B$B邪恶的巫毒夺走了他们的神智，兄弟。但要破除邪恶的巫毒，你需要付出鲜血与良善的魔精。这两样代价都可以在祖尔哈塔偿付。你会在那里找到带着梦境魔精的代言人甘霍塔。不远处你会找到督军汉森托，他的血正是你需要的。他是这一切蠢行的根源，而那正是拨乱反正的正途！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- There be something other than demons on my mind, mon. My tribe, my own people. Lost to the
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7002, '有些士兵正忙着为马厩管理员捕捉狼，另一些人则要备齐骑乘所需的简单装备——我说的自然是坐骑挽具。$B$B你必须去猎杀本地的山羊，正是雷矛骑兵用作坐骑的那种山羊！$B$B杀掉它们，把皮交给我。等我们把皮凑齐，就能为骑兵缝制挽具。霜狼狼骑兵将再度驰骋！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- While some of our soldiers are busy capturing wolves for the stable master, others must pr
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7385, '你也可以一次献上更多从敌人身上取来的鲜血。一整加仑的分量，我乐意收下，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You have the option of offering larger quantities of the blood taken from our enemies. I w
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7386, '有时你会连续数日甚至数周陷于战斗之中。在这样漫长的征战里，你可能积攒下大批的霜狼风暴水晶。$B$B议会收下这样的献礼，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- There are times which you may be entrenched in battle for days or weeks on end. During tho
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (7813, '和大多数布料一样，我们的羊毛储备已经见底。目前库存的状况是，我们只需要你提供总计六十块羊毛；有了其他人的支持，我们应当能够达成目标。$B$B顺带一提，像羊毛这样慷慨的馈赠，必定能提升你在当地的声望！如果你身上正好带着六十块羊毛布，并愿意捐献出来，我现在就可以收下。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- As with most other fabrics, our stocks of wool are at an all-time low. Our stores are such
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8184, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8185, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8186, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8187, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8188, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8189, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8190, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8191, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8192, '只要有合适的材料，赞扎就能制作古老的巨魔附魔。$B$B第一件是原始的哈卡莱神像，必须从最强大的哈卡莱副官——金度和血领主——手中夺得。$B$B第二件是被扎穿的巫毒娃娃。这些东西散落在这片污秽之地的垃圾堆里。去那堆被施了咒的巫毒堆里找找。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Zanza can create the ancient troll enchantments with the right components. $B$BThe first i
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8195, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8238, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8239, '我在寻找被称为「部族硬币」的力量典范。它们是祖尔格拉布的各类居民使用的货币，每一枚都蕴藏着微妙而强大的魔精。$B$B共有九种不同的硬币。其中一些是我的同胞们所追寻的，用来为赞达拉的英雄们换取各种护甲。若你手上有多余的，我可以用一枚荣誉徽记换取你三枚硬币。你可以用这些徽记找商人林沃沙换取物品，他为我们的英雄提供特别的装备。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I seek the Paragons of Power known as the Coins of the Tribes. They are the currency used 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8271, '本地的冰斧巨魔是残忍的野人，他们最乐意的事莫过于把我们的骨头丢进那锅恶心的炖菜里。$B$B我们必须让他们见识我们的力量！$B$B我们从他们的洞窟里找回了记载其首领层级的典籍。这些古物显示，他们的首领「血怒者科尔拉克」惯于隐藏自己，直到有了现身的理由。$B$B科尔拉克死，冰斧部族便亡！杀了他再回来。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The indigenous Winterax trolls of the region are ruthless savages that would love nothing 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8272, '入侵的雷矛并非此地唯一的威胁，士兵。山谷中的战争在两条战线上进行。食人的冰斧巨魔同样在争夺权力。$B$B他们的首领是「血怒者科尔拉克」——一头残忍而狡诈的野兽。$B$B对科尔拉克的一击，可能就是击垮冰斧部族的沉重打击。杀掉那畜生，你会得到奖赏！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The invading Stormpike are not the only threat in the region, soldier. The war in the Vall
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8383, '奥特兰克山谷的战斗仍在继续，$N！近来你可尽了自己的一份力，$N？') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Battle in Alterac Valley rages on, $N! Have you done your part as of late, $N?
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8384, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8385, '啊，$N。我希望你继续把经验带到各个战场上去。我们许多前线的将士都敬仰你这样久经沙场的老兵。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Ah, $N. I hope you continue to lend your experience to the different battlefronts. A lot o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8386, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8387, '奥特兰克的战斗仍在继续！你必须重返奥特兰克山谷，再次把入侵者逐出霜狼的领地，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle for Alterac rages on! You must return to Alterac Valley and once more drive the
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8388, '许多勇敢的战士都仰望着你，$N。在与联盟的战斗中，你始终是众人的榜样。你此番远行带来了什么消息？') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Many brave fighters look up to you, $N. You continue to be an example for all in the fight
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8389, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8391, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8392, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8397, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8398, '打赢一场战争，不只是比对手更聪明、更能打。胜负往往就取决于谁能造出更多的军备。$B$B我们在阿拉希盆地拥有的，是可供先夺下的一方使用的大量资源。$B$B若联盟获胜，我们的部队就能多出许多刀剑与长矛。若部落获胜，那些刀剑和长矛照样会被造出来——只是矛头会对准我们！现在正是为联盟在阿拉希盆地出力的时候，$N。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Winning a war is about more than just outsmarting and outfighting your opponent. Victory o
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8404, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8405, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8406, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8407, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8408, '银翼哨兵与战歌先锋之间的战争，源于兽人对森林的破坏。不过，要保卫这片森林的理由远不止热爱自然。$B$B这片森林构成了一道战略屏障，使灰谷能够抵御大规模进攻。没有它，阿斯特兰纳撑不过一两天就会被并入贫瘠之地。$B$B为对抗战歌先锋尽你的一份力，$N！为了联盟！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The Silverwing Sentinels are at war with the Warsong Outriders due to the destruction the 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8431, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8432, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8433, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8434, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8435, '在战歌峡谷中与银翼哨兵的这场战斗至关重要。联盟打着保护一片本不属于他们的森林的幌子，企图夺走部落最大的一处木材来源。$B$B别让他们的图谋得逞，$N！带着你为部落建功的凭证回来见我！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The battle in Warsong Gulch against the Silverwing Sentinels is of great importance. Under
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8440, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8441, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8442, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8443, '我们与联盟的冲突已升级为真正的战争。到这一步，双方都不再需要、也不再期待以虚假的借口开战了。$B$B阿拉希盆地的战斗，说白了就是一场资源之争。资源要么被联盟夺走用来对付我们，要么被我们夺来支撑战争。帮助污染者维持我们所需的资源供给，$N！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Our conflict with the Alliance has escalated to a true war. No longer are false pretenses 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8595, '我看得出，你不是普通的凡人，$n。你对抗上古之神的胜算虽然微乎其微，却比我们此刻要大。毕竟，他防着龙族登门，却没料到会遇上你这样的人。$b$b正如阿纳克洛斯与鹿盔在千年前以凡人与龙族的联手击败了其拉虫人，我们也来立下盟约。赢得青铜龙军团的信任，你便赢得我们的信任。到那时，我们才会把你塑造成真正的勇士。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I see that youre no ordinary mortal, $n. Your chances against the Old God, however infinit
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8608, '你回来了？有意思。如你所见，我仍在为安其拉之战募集物资。也就是说，我还得请你再出去一趟，替我收集一捆魔纹绷带。期待你归来，$C。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You returned? Interesting. As you can see I am still collecting for the AhnQiraj war effor
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8751, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8756, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (8761, '我从未见过如此坚毅之人！青铜龙军团再赐你一道附魔——是时光守护者本人要求的！$B$B把你的印章戒指交给我，我好做相应的调整。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The T
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (9142, '规矩你懂，小子。一枚英勇徽记换一份工匠的委任状。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You know the drill, kid. One valor token gets you a craftsmans writ.
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (39980, '什么样扭曲的心智才会去袭击平民？这场冲突中已有无数无辜者丧命，但有些人却专门以伤害无力自保者为乐。不只是男人，还有女人和孩子。这样的暴行不能不予回应。我们必须出手阻止。找出过去一天内不义击杀数最多的玩家，终结他们的屠戮。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- What kind of deranged mind attacks civilians? Countless innocents have died in this confli
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (39981, '大屠杀有什么荣耀可言？没有，那是疯狂，而我们有责任阻止它。要阻止联盟与部落之间的战争吞噬我们所有人，就必须除掉那些最热衷于此的人。找出过去一天内荣耀击杀数最多的玩家，终结他们的嗜血。唯有如此，才能有和平。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- What is honorable about mass slaughter? Nothing, it is madness, and we have a duty to prev
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (40739, '那么，又来换一根巨型香蕉了，是吧？我懂：那味道实在太惊艳，我自己也吃不够！$B$B我只需要你带来三根熟透的特尔阿比姆香蕉和一份梦境之尘。材料一到，我就能再为你转化三根大香蕉。没错，就这么简单！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- So then, back for another Gargantuan Banana, are you? I know: The flavor is so spectacular
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (40740, '我改良了转化工艺，甚至扩建了实验室！一次造出多根巨型香蕉如今完全可能。当然，我需要的还是启动流程所需的材料。$B$B要造十五根巨型香蕉，我需要十五根熟透的特尔阿比姆香蕉，以及五份梦境之尘。若你想要一捆那种巨型香蕉，就把材料带来，我让你美梦成真！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I have refined my transmutation process and even expanded my lab! The ability to create mu
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41274, '你能感受到吗，$C？那弥漫在空气中的爱与倾慕的芬芳？那些热恋中的鸟儿彼此分享的喜悦与迷恋？见证爱在艾泽拉斯蔓延的奇迹，没有什么比这更让我心跳加速了！$B$B你的眼睛出卖了你的心，我读你就像读一本摊开的书。我能看出你渴望了解更多，甚至亲身去体验这份情感。爱有千般形态，并不总如人所想的那么分明。就连我这位爱的传令官，也常为我的箭所选中、蒙受爱的祝福之人感到意外！爱，真是个谜！$B$B不必再找别的证明——只看过去被我的箭射中过的那些人就够了。给我带来一份他们那份独特的爱与倾慕的信物，把这些纪念品带到任意主城交还给我。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Can you feel it, $C? The sweet fragrance of love and admiration that permeates the air? Th

-- ---- 第 2 批：16 条任务（珠宝加工师成长线 41275-41290）----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41275, '$N！你有空吗？你的珠宝加工手艺出类拔萃——我门下少有弟子仅凭我的教导就能达到这样的水准。不用大师也看得出：你天生就该把这门手艺磨炼到极致。$B$B虽说你已远远超出我的期望，可惜我能教的也仅止于此了。但这并不意味着你旅程的终点。还有比我更能胜任的导师，其中一位正是我的好友。也许你已与他相识——他有些多疑、爱抱怨，但只要稍加帮助，他就会倾囊相授。$B$B若你想专精此道、成为珠宝加工大师，就去秘法区找塔瓦斯德·基瑟尔吧。他的指点将为你在这行铺就前路。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N! Do you have a moment? Your skills in jewelcrafting are exceptional, rarely any of my p
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41276, '$N，再次见到你真是太好了。我注意到了——你自然也注意到了——你在这门手艺上的进步堪称飞跃！说真的，我已许久没见过如此天赋异禀的双手。可惜这也意味着我的教导到此为止了。不过你求知的热切显而易见；好在我还能最后帮你一次。$B$B若你想在珠宝加工上更进一步，就去卡加斯找我的好友加卡尔。险恶的荒芜之地不是我这种尸体该待的地方，但像他那样结实的巨魔，再恶劣的环境也应付得来。去找他的路上务必小心，愿你一路平安。$B$B<古尔迈尔短促而诚挚地鞠了一躬。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N, what a splendid sight to have you here with me once more. I have noticed - and you sur
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41277, '$N！你有空吗？你的珠宝加工手艺出类拔萃——我门下少有弟子仅凭我的教导就能达到这样的水准。不用大师也看得出：你天生就该把这门手艺磨炼到极致。$B$B虽说你已远远超出我的期望，可惜我能教的也仅止于此了。但别灰心——我自己的师父瑟格伦，或许能在我不及之处助你一臂之力。$B$B若你想专精此道、成为宝石切割大师——那门操控宝石以增益自身本领的技艺——就去找瑟格伦。他属于一个比我们现今任何文明都更古老的团体，却选择了隐士的生活，独居于荒芜之地的荒野。去古城科尔桑的废墟附近寻他。他不与任何人交谈，但若你把这块水晶拿给他看，我向你保证——他会听你说明来意。路上务必小心，去那片荒凉之地的旅途十分凶险！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N! Do you have a moment? Your skills in jewelcrafting are exceptional, rarely any of my p
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41278, '$N，再次见到你真是太好了。我注意到了——你自然也注意到了——你在这门手艺上的进步堪称飞跃！说真的，我已许久没见过如此天赋异禀的双手。可惜这也意味着我的教导到此为止了。不过你求知的热切显而易见；好在我还能最后帮你一次。$B$B若你想在宝石学上更进一步，有个人或许能助你达成志向——一个神秘莫测的人。他比我所知的一切都更古老，属于一个曾掌控艾泽拉斯矿物知识的古老团体。因此他极重隐私，也就是说，他多半不会与你交谈。来，带上这块水晶。它是我曾在他门下受教的凭证，也能让他知道你可以信任。路上务必小心，愿你一路平安。$B$B<古尔迈尔短促而诚挚地鞠了一躬。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- $N, what a splendid sight to have you here with me once more. I have noticed - and you sur
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41279, '<你猜想，那该算是这位土灵脸上的笑容。从巨人身上取下的粗糙宝石，在他宽大的手掌里显得很小。他只点了点头，便示意你再次跪下。$B$B当他的手掌再度按上你时，眼前的景象清晰了许多，尽管这过程仍令你吃力。三颗宝石浮现在你内心的视野中。幸好你认得它们：一颗烬石、一颗星红宝石、一颗黄水晶。接着，你看到这三颗宝石被切磨成一种你从未见过的刻面。你凝神细看，把那些动作一一记下。这份智慧已深植你心。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <You assume what you are seeing is a smile on the Earthens face. The rough gemstone from t
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41280, '<视野恢复时，瑟格伦正摆弄着双手之间的什么东西。凑近一看，他毫不费力地把一颗星红宝石切成了你方才见过的刻面。他把宝石放到桌上时，手中又可见另一颗宝石——一颗黄水晶。他重复了同样的过程——接着又用烬石做了一遍。$B$B手艺人用生硬的目光指指你，指指他的作品，然后摊开空着的手掌。你琢磨片刻，终于明白他的意思：他要你把刚学会的三种切割各做五遍。$B$B应该不太难，对吧？>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Regaining your vision, Thegren is tinkering with something between his hands. Upon closer
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41281, '<不必他示意，你便跪下，接受新师父教诲的下一幕幻象。$B$B洁白的厅堂、无尽的瀑布，一股暖意充满你的脑海。在遥远的西方，卡利姆多大陆上，凄凉之地的山峦深处，正是这幻象的源头。曾是圣地的玛拉顿洞窟中，藏着你下一个目标：又一个巨人，这一回是纯净大理石之躯。你需要取回他石身上的一块石板。$B$B你重新站起，向瑟格伦点头，他只是以拳捶胸，便又埋头于自己的工作。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Without having to gesture anything, you kneel down to receive the next vision of your new
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41282, '<瑟格伦面前的桌上摆着三样东西：你从波尔加斯特身上取下的命脉宝石、兰斯利德的大理石纹石肤，以及一块似乎不受岁月侵蚀的精致布料。你仔细端详了许久，转向瑟格伦——他只是面无表情地看着你，不过他那张石雕般的脸本来也看不出什么。$B$B看来这是你最后的考验。用你学到的宝石切割本领，把这颗灼热的石头切磨成完美的形状。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <On the table before Thegren are three things layed out. The Lifeblood Gem you took from B
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41283, '好吧，听我说，我就跟你实话实说。我教你那些秘传工艺，绝不是因为我乐善好施。我向你保证，绝对不是。相反，你要帮我……补充库存，作为交换，你会得到关于我金饰加工的一小份真传。行不行？就这么定了。$B$B请尽快把下面这些东西给我带来，我可不是那种愿意久等的人。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Alright, listen, let me be honest with you. I will not teach you my secret crafting techni
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41284, '信不信由你，住在山底下并不代表你的库里就有源源不断的宝石。而且要是有些子虚乌有的谣言让你没法在这儿做正当生意，那更是雪上加霜。要是我还在诺莫瑞根，这些事都会容易得多，相信我。可话说回来，宝石是珠宝加工的命根子——没有宝石，就没有珠宝，没有买卖，没有钱，付不起房租。你懂的。眼下我急需讨房东欢心，所以需要不少那种闪闪发亮的小宝贝来弥补损失。$B$B我们想到一块去了吧？当然。把下面这些宝石给我带够，我会分你点小东西。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Believe it or not, but living under a mountain does not guarantee you a steady flow of gem
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41285, '不管别人跟你说了我什么——全是谎话！我百分之百、从来没有给任何人做过什么受诅咒的东西。我对手艺有操守，也立过誓！别问我跟谁立的誓。绝对保密。而且绝对、绝对不心虚。$B$B话说回来，似乎某个倒霉冒险者的厄运现在落到我头上了，又一次往我名声上泼脏水。有个大胆的法师找上门来，要一条能增强法术的项链，好去北方那座新近重新发现的吉尔尼斯城探险。我当然照办，给他做了一条——反正房租到期了。可他在那鬼地方的探险，结局嘛……对他算不上好。糟糕的是，他那帮冒险者同伴现在把他的死算在我头上，在铁炉堡到处说我在项链上附了邪咒！$B$B$N，我要你亲自闯一趟吉尔尼斯城，把那条项链给我带回来！我最不愿看到的，就是有人拿它当假证据来对付我。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Whatever youve been told about me - its all lies! I one hundred percent NEVER made any sor
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41286, '到此为止了，好心的旅人。我能教的，你在别处也差不多都能学到。不过，若你求知的渴望不肯就此打住，那我就告诉你我这些巧妙本事的来处。$B$B按理说这话我不该说，但你帮了我的大忙，我不能让你空手而去。向西去，在凄凉之地那片险恶的平原上，你会找到我自己的师父，他离群索居。虽说他喜欢清静，但我知道他不介意有人作伴。若他一开始不搭理你，别泄气——对于那些想求知识的人，他最看重的正是执着！$B$B去找一座俯瞰大海的高塔，那是我最后一次见到他的地方。既然话都说到这儿了，你最好快点走，免得我房东以为我在搞黑市买卖！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- This is it, good traveler. There isnt much more I could teach that you couldnt learn elsew
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41287, '老实跟你说，在这荒野里，我们的物资并不充裕，没法正经教你。我可不像奥格瑞玛那些矮个子绿皮朋友那样资源无限。不过，这难不倒我们。幸运的是，这片土地自然资源丰富，你可以把它们变成上课要用的材料。$B$B就当是一次测验，看看你到底有多少本事。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I will be honest with you, out here in the wilderness, our supplies are not as plentiful a
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41288, '你自然知道，宝石、贵重石料与矿物是珠宝加工的根本。没有它们，做出时髦的饰品固然还是可能的——但说实话，那还有什么意义？依我之见，一颗精致的宝石，甚至一颗华丽雕琢的宝石，才是赋予首饰目的与意义的关键。$B$B给我带来足够多的艾泽拉斯宝石，我们好一起分析它们的特性。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Like youll surely know, gems, valuable stones and minerals are essential to jewelcrafting.
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41289, '我族在金银加工与镶嵌点缀方面有着悠久的历史，无论是可拆卸的还是永久的。我固然会与你分享古老的赞达拉金饰加工传统，但把眼界扩展到其他知识来源同样重要。$B$B我要你去钻研的，是人类制作仪饰章的做法。向北去，离我们那些被遗忘者盟友的领地不远处，你会找到吉尔尼斯这个国家。据说它是旧时代的遗存，如今刚刚向那些勇于挑战其凶险之人敞开。在它那山脊般的高塔之上，便是吉尔尼斯城——据旅行的冒险者说，那是个商业、贸易与庆典之地。$B$B你会在那里找到一份适合我们分析的东西。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- My people have an extensive history about goldsmithing and bedazzlements, be it removable 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41290, '好心的旅人，谢谢你让我能重拾这门许久无法施展的手艺。我曾立誓要继续磨炼技艺，可这些年为部落效力，让我再也无法顾及这个誓约。不过，若像你这样的冒险者再多来几位，或许我终究还能做到。$B$B为了答谢你及时的帮助，让我好好报答你——告诉你我是在哪里练就金饰加工本领的。向西去，在凄凉之地那片险恶的平原上，你会找到我自己的师父，他离群索居。虽说他喜欢清静，但我知道他不介意有人作伴。若他一开始不搭理你，别泄气——对于那些想求知识的人，他最看重的正是执着！$B$B去找一座俯瞰大海的高塔，那是我最后一次见到他的地方。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Good traveler, thank you for letting me practice this craft I had long been unable to. I h

-- ---- 第 3 批：12 条任务（巧匠与收藏家线 41291-41302）----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41291, '这么说，你非要学这门金饰加工的手艺不可？我通常亲自挑选弟子，可是……既然我从前的一名学生推荐了你，甚至让你一路探寻到此，我实在无法拒绝你的请求。我们本可以立刻开始，只是眼下有一桩小小的麻烦。我在海滩上收集被浪冲上岸的矿物时，不幸弄丢了我珍爱的珠宝匠工具包。一头海巨人惊到了我，我只得弃包而逃，此后一直没能找到安全的时机取回。我的战斗岁月早已过去，所以若你想学我的手艺，就得替我把工具包取回来。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- So you are adamant to learn the art of Goldsmithing? Usually I pick my pupils, yet… If one
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41292, '你可以称我为巧匠，年轻人。数千年前伟大的埃瑟瑞拉斯城陷落时，我舍弃了从前的名字。此后我游荡在卡利姆多的荒野间，把智慧传授给凡人族裔中我认为值得受教的人。派你来的那位朋友——尽管听来难以置信，他正是我教过的弟子之一。看来他对这门手艺的热爱并未随时间消退，这倒令人欣慰。$B$B你想学习那些流传数百年、在种族、文明与世代之间传递的金饰加工技法？那就向我证明你的本事。让我看看，你能把大地的血之声听得多清楚。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- You may address me as The Artificer, young one. I abandoned my previous name when the grea
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41293, '你是说，他教了你一些本事。那么请放心，他掌握的知识大多是我传给他的。他或许是个熟练的珠宝匠，但这门手艺中更隐秘的诀窍并不在他那里。若想潜入一门技艺的深处，就必须对它的表层有透彻的理解。$B$B这正是我要你做的：把你对金饰加工的基础知识展示给我看，我才知道该从何处教你。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- So he taught you some of his skills, you say. Well, rest assured, most of the knowledge he
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41294, '真正的匠人会把生命的方方面面融入作品：生、死、天与地、在我们世界中起作用的各种元素。你或许已经知道，艾泽拉斯的宝石蕴含着潜藏的魔力与元素属性，落到对的人——或错的人——手里都会极为强大。$B$B向我证明，你能在制作首饰时恰当地驾驭艾泽拉斯宝石中的能量。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- A true artisan encompasses all aspects of life into his work. Life, death. Heaven and eart
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41295, '过去几百年里我有过许多弟子，说实话早记不清有多少了。但其中有一位，永远鲜活地留在我的记忆与心里。那是个年轻的精灵，肤色白皙，我此前从未见过那样的。她对金饰加工的好奇与热切无与伦比——那正是我在她少年心性中所欣赏的特质。$B$B她毫无偏见地对待这门手艺，把它视作心灵与灵魂的表达。当她完成最后一件作品——一柄品质非凡的法杖——冒险之风便把她卷走了，从我身边带走。我曾盼望她终有一日回来，哪怕只是来看看，可惜重逢终究没有发生。$B$B她的存在——以及她的不在——在我身上留下了印记。因此我要求每一位后来的弟子都具备她对手艺那份澄明的眼光。向我证明，你能追随她的榜样。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Ive had multiple pupils in the past centuries, and frankly Ive lost count on how many ther
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41296, '我的人民已经分裂。逃离故土以来，为了寻求安宁与栖身之地，我们历经磨难。避难所的同胞们仍然坚韧，紧抓着希望不放，但那些失落者就不是如此了。疯狂已深深攫住他们的心智，根须早已无从切除。他们徒劳地想要回到德拉诺那片地狱般的故土，于是收集德莱尼水晶——那种来自那里的强效宝石——却不知道自己根本无法正确使用它们。可事情当初并非如此。$B$B他们之中曾有一位强大的裂隙行者，名叫库米沙，他与荒芜庇护所那些发狂的德莱尼人分道扬镳。如今他游荡在南方那片险恶的平原上，追寻神话与传说。我要的正是他关于我们神圣水晶的学识——若你能说服他加入我们，请务必一试。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- My people have been divided. Weve endured much on the escape from our home, in search of s
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41297, '我把那些失落者抛在了身后。他们的首领已成了淌着口水的蠢货，对着神圣的德莱尼水晶垂涎三尺，忘了自己真正的潜能。桑夫·克拉也不例外，希望毒害了他和他追随者的心，让他们看不见自己正困在一个贪婪的世界里。你也是。否则，你站到我「收藏家库米沙」面前，还能是为了什么？不就是为了从我这里夺走你想要的东西？但我了解你和你的同类——而正是你的贪婪，会推动我的野心。$B$B这些被诅咒的土地上游荡着失去心智的德莱尼人，他们使用裂隙穿行的魔法，却没有驾驭它的本事。在无止境地搜寻德莱尼水晶的过程中，他们失了神智，像虫豸一样翻刨沙土。全都是疯狗！他们袭击了我的营地，偷走了一批珍贵的宝石。把他们杀光，取回我的东西，我或许会赏你几分用处。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I left the lost ones behind, their leaders have become bumbling fools drooling over the sa
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41298, '<库米沙研读着那卷外族卷轴，他那不断变幻的身形忽隐忽现。读完之后，他愤怒地把羊皮纸撕成碎片。>$B$B卡拉托卡尔！他们在想什么？这是对所有德莱尼的亵渎，亵渎！他们像工蜂一样在这片死亡之地上游荡，令人担忧，倒还不算危险。可他们的目的，就危险得多了。据这份经文所述，你遇到的那些追寻者正在为一个卑劣的生物收集德莱尼水晶——一个名叫马托加的裂隙行者。单是这一点就已冒犯了我的志向，而他的真正目的更是令人作呕，必须阻止。若他能把水晶带回德拉诺，我们唯一归乡的途径就会断绝——我们将被判在腐烂与衰败中了此一生，永远被囚禁，再也见不到家园。$B$B你不会让这种事发生的，因为库米沙会赐予你所求之物；代价是他的首级。他在我营地西北方等候他的追寻者们。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Kumisha is studying the foreign scroll, his shifting body fading in and out of view. Afte
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41299, '拿去，把这卷卷轴带上。你，还有那个天真的桑夫·克拉，都能从上面找到我关于德莱尼水晶及其用途的学识。他尽可以照自己的打算去做，只要不妨碍我的计划。听从我的警告对他最有利，否则他会落得和马托加一样的下场。$B$B至于你，我只有一句话：除非你愿意继续为我效力，否则我不想再看到你。若是不愿，就滚吧。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Here, take this scroll. On it you and the naive Sanv Kla will find my knowledge of Draenet
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41300, '哦，糟了！一个侏儒能倒霉到什么地步？我犯了个可怕的错误，现在代价是我的脑袋，或者更糟——我的家！$B$B简单说，我的钱袋干得见底了，见底得厉害！我当时走投无路，就接受了一个来路可疑的商人的提议，他许诺给我成堆的黄金。可等他第二次上门，身边却带着两个吓人的打手，还向我索要远超约定的货物！我苦苦解释我的库存根本不够他要的，可他们充耳不闻——现在他们还在威胁我。威胁我！慷慨无双、无人能及的塔瓦斯德·基瑟尔！$B$B求你帮我解这个困局！我保证，你会得到应有的回报。那些恶棍往贸易区去了，我敢肯定这帮贼就藏在外环那一排排房子里！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Oh, this is bad! Just how unfortunate can one single gnome be? I made a horrible mistake a
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41301, '那么，你来做什么？来好言好语求我别再纠缠你那位不肯履约的朋友？还是打算用更……直接的办法解决问题？不管哪种，我都遗憾地告诉你，都行不通。期限是我们这行最看重的东西，而那些没能按期交付的人……$B$B<他朝站在你身后的两名凶悍护卫比了个手势。>$B$B不过，我是个待客殷勤的商人，不会因为对令人失望的交易对象心存恶感就放过机会。所以我给你个提议：把塔瓦斯德还欠我们的货物交付双倍，我和我的同伴们可以考虑放过他。这提议很合理吧？我要是你，就会尽力答应下来……') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- So what are you here for? To ask me nicely to stop harassing your friend who doesnt want t
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41302, '<莫索格用放大镜仔细检视着货物。他查验的时候，你能感觉到那两名保镖就贴在你身后喘气。这位来路不正的商人查验完毕，把首饰收进箱子，扔给你一袋钱。>$B$B和你做生意很愉快。我建议你现在就回你朋友那儿去，你们俩以后都别再在这儿露脸。滚吧。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Motsog inspects the wares meticulously with a lens. While he does so, you can feel the bo

-- ---- 第 4 批：16 条任务（哥布林线与地脉调查线 41303-41319）----

INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41303, '灾难，这简直是场灾难！一场金钱上的末日降临到我头上；我的名声被毁了，我的声望也荡然无存。我那些值钱的首饰正运往藏宝海湾拍卖，其中有一枚格外贵重的大戒指。我以为它们已经平安抵达那座港口城市，就没多想继续干活——却不知道它们压根儿没离开过棘齿城！如今我成了那些体面商人和拍卖师的笑柄，他们正乐呵呵地嘲笑着我的无能。$B$B伙计，你能帮我收拾这个烂摊子吗？我信得过的承运人格里兹比踪影全无，而我丢不起那些无价的杰作。既然没有线索，不如先在棘齿城里四处打听打听。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- A disaster, thats what it is! A monetary apocalypse is upon me; my name sullied and my fam
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41304, '我认识格里兹比很久了，那家伙很爱交际，你知道的，朋友一大堆。干这行自然如此。他来到码头时我正在忙物流的事，因为下一班船还早得很，我们就聊了几句。$B$B我们正闲聊打发时间，另一个地精凑了上来，那样子活像见到了失散多年的亲兄弟。他俩关系一定很近，因为格里兹比看上去也跟他很熟。他们聊什么我没听清，但隐约听到他们说要往南去，不知为了什么。$B$B已经过去好些时候了，我担心格里兹比凶多吉少，请你务必确认他是否平安。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Ive known Grizzby for a long time, a sociable bloke, yknow, lots of friends. Comes with th
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41305, '这份契约我要亲自带给纳特，他该知道我们以前的雇主在科赞有什么图谋。要是做得到，我真想大摇大摆闯进幽暗城，把他们的贸易亲王扔进最深的贫民窟里去。可我做不到，所以只能把手头能做的做到最好。$B$B首饰被偷，物资又将耗尽，下一次拍卖我几乎拿不出任何东西——而我在那场拍卖上必须拿出一件响当当的物件，否则我的名声就彻底完了。我看得出你手巧又有天赋，愿意再帮我一次吗？$B$B我要的是一颗大得夸张的宝石。来斯帕克沃特的旅人们传说，血色十字军手里有一颗拳头大的红宝石，我想他们的首领就随身带着。另外，还要一条素净的金项链，好让我把红宝石镶上去；这点活你自己就能敲打出来。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I will bring this contract personally to Nert, he should know what our former employers ar
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41306, '我跟你讲，我这人就是命里带霉。你看，如今贸易航线上四处都是海盗，用船运货就跟把货仔仔细细系上蝴蝶结、亲手递给那些亡命徒没什么两样。所以显然不行。另一个办法是走陆路，风险一样大，你肯定明白我在说什么。$B$B不管怎样，我选了后一条路。因为我真的、真的必须把这批货送到，我就在棘齿城找了个最吓人的食人魔，付钱让他一路护送我去热砂港。可惜我们遭到亡灵野猪人的伏击，食人魔和我那批宝贝货全被他们掳走了。$B$B我快绝望了。你能去剃刀高地帮我把货取回来吗？我不觉得货还在那个食人魔护卫身上，但要是他还活着，他会知道货在哪儿。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I am cursed with bad luck, Im telling you. You see, with all the pirates roaming around th
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41307, '萨赫希很抱歉，没能办到。萨赫希不够强壮，保护不了绿色的朋友，可恶的野猪人把萨赫希带到了这里。他们想吃掉萨赫希，可是妈妈说萨赫希太胖了，也许不太好吃。$B$B你要是来找特拉西斯的箱子，它就在这儿，可是他们打可怜的萨赫希、逼他快走时，石头全掉出来了。现在那些亮闪闪的宝石都在可怕的僵尸和鬼魂手里！萨赫希想回家，你能帮萨赫希把特拉西斯的宝石收起来、送到塔纳利斯那个小侏儒那里吗？特拉西斯说她在海边的小镇等着这个箱子！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Sahrhee is so sorry he failed. Sahrhee was not strong enough to protect little green frien
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41308, '好吧，当我刚才什么都没说。我绝对不会再从他那儿订货了。这些宝石的表面全是脆的！怎么会这样？他对它们做了什么？$B$B<你把宝石如何落进几具亡灵肚子里、又如何被它们的体液侵蚀的经过讲给凡兹听。>$B$B呃，你不用讲得那么细。真恶心。好吧，真是妙极了。现在我手上又多了一堆活，而这是我眼下最经不起的。所幸你在这儿能搭把手。哦，别摆那副表情，我付你钱，不找特拉西斯要——他最好别在近期带着那张脏脸出现在这儿。$B$B要修好这些宝石，得用点更有劲的东西，普通的宝石油在这儿不顶用。往南不远处的海边有个小湾，你在那儿能找到一个……就说是我的一个生意伙伴吧。把海岸边钢颚钳嘴龟身上的油腺、一份强效秘法精华和一个水晶瓶带给他。就说是我让你去的。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Okay, scrap what I just said. I will definitely not order from him again. All these gemsto
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41309, '<扎拉什吉把油腺挤进水晶瓶里。他沙哑地低吟着含混不清的词语，施出一道陌生的法术，瓶中的液体泛起鲜亮的光芒。>$B$B拿去吧，外乡人。这油能封住宝石表面的裂纹，同时又不妨碍精细的切割。现在走吧——我允许她常来同我往来，可对你，我就不能这么说了。我或许比我那些同胞更好客，但这不代表我的耐心没有尽头。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <Zalashji squeezes the oily glands into the vial. Muttering unintelligible words under his
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41310, '<你找到的这本书不像周围其他典籍那样古老。书上装饰着肯瑞托的印记，你猜想它必定属于某位强大的法师。$B$B翻过书页，你判断这是一位名叫卡德加的法师的日志——你从前听说过他。他曾是守护者麦迪文的学徒，也是洛萨之子的一员，那支队伍在二战期间率领联盟远征德拉诺。$B$B你期待又揭开一个谜团，于是更专心地研读起其中的内容。>') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- <The book youve found looks not as old as the rest of the tomes lying around. Embellished 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41311, '阿尔萨斯奉他那群恶魔主子的命令围攻达拉然时，我就在场。梅内希尔为盗取麦迪文之书犯下滔天罪行，他的军队同时洗劫了城市，抢走了我们存放在宝库中的其他危险遗物。为保卫这座魔法之城，我们拼死抵抗，我曾直面一头寻求毁灭与混乱的强大末日守卫。$B$B你要找的若是坦拉尔之握，那就必须找到那头末日守卫。达拉然陷落后，我疗养期间，其他幸存的法师讨论过阿克蒙德和他军队的下一个目标——结果他们向西而来，正是这片土地，为的是追逐世界之树诺达希尔。若那头末日守卫仍在艾泽拉斯，我猜他正在某个恶魔横行的深渊里谋划复仇，就在海加尔山附近。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- I was there when Arthas besieged Dalaran under the order of his demonic overlords. While M
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41312, '当年在达拉然由肯瑞托保管时，我曾仔细研究过那件握物的形制、功用与用途。麦迪文虽是个讳莫如深的人，但他的法器与饰物上都带着同一种魔法标记，哪怕不熟悉守护者的法师也能感觉得到。研究过程中我得出结论：那件握物是某个宏大之物的一部分，而那个宏大之物又是更伟大之物的一部分。从它的形制判断，其顶端本应嵌着一颗巨大的宝石。$B$B若你在那座闹鬼的高塔中遇见这样一颗宝石，我有信心把这件古物复原如初。不过要做到这一点，我需要一个强大的奥术聚焦物来引导我的能量。守护艾泽拉斯魔法的蓝龙军团掌管着这类物件，但只有他们中最强大的成员才会随身携带。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- When the clutch was in the Kirin Tors safekeeping in Dalaran, I studied its form, function
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41313, '这片土地魔力充盈。我到此研究有许多原因，其中之一便是贯穿大地的众多地脉。强大的奥术能量自它们流淌的脉络中涌出，吸引着此界与他界无数渴求法力的居民。我想更清楚地弄清，为何这片被遗忘、被诅咒的土地会成为这种现象的所在。你眼中露出好奇——你打算协助我的研究吗？$B$B塔中另有事务缠身，所以若你愿意出去为我收集一些材料，我会给你相应的报酬。我需要的是地脉能量的结晶构造。我的学生在此地以东和以南各找到一处。我猜当地的蓝色龙人和堕落的血精灵是我们最好的线索。就从那里查起吧。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- This land is rich in magic. Numerous reasons brought me here for my research, and the many
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41314, '这两块水晶的整体结构完全相同，只有那块朱红的不同——当我用一点自己的魔力与之共鸣时……$B$B<克希雷姆把极微量的一丝法力导入红色水晶，顿时迸出猛烈的电火花与闪电。>$B$B听着，我们现在掌握的事实是：蓝龙军团不知出于何种我们尚未查明的原因，从门纳尔湖收集生长被某种手段人为加速过的地脉水晶。当地的血精灵也持有这类水晶，只是形态不同、更不稳定。这两件事是否相关，正需要我们去查清。$B$B我会继续测定这些水晶的稳定性，你则去替我取回一件珍贵的遗物——完成研究需要它。我从前的一名学生愚蠢地以为，把它带出我的塔不会有人察觉。萨纳斯告诉我，她匆匆往东去了木喉要塞附近，无疑是仗着与他们的交情藏身其中。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Both of these crystals have the identical integral structure, except the vermillion one - 
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41315, '聚焦宝珠既已取回，就只剩下最后一件事需要确认了。来，带上这些水晶和宝珠，把它们放到我塔前的基座上。我在宝珠上施的法术会与地脉水晶产生反应——但愿如此——从而证实我对它们本质的推论。$B$B别害怕，我会在塔中注视着你，必要时出手相助。以你的本事，我们不必太过担心，但别忘了：谨慎是智者的命脉。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- With the focus orb returned, there is but one last thing we must assure ourselves of. Here
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41317, '我大半辈子都在研究这套传说中的珠宝加工百科。据传它们出自一个古老社会之手——我们如今所知的人类种族的先祖。考古学家正发现越来越多他们的废墟，人们称他们为阿佐萨。至今只找到五部他们的典籍，据说共有十一部。我的一位同样古老的熟人真的打开过一部——他把里面的情形告诉了我。他说那些书是用元素符文封缄的，那是艾泽拉斯元素生物口中念出的远古词语。此后我便一直在钻研它们，而这道锁上的火焰符文，看来正是布拉兹符文。$B$B我们需要一块与那道符文同调的元素生物的碎片。听说黑石山最深的洞窟——熔火之心里满是烈焰元素。我相信在那里最有可能找到我们要的东西。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Ive been researching this legendary encyclopedia of jewelcrafting most of my life. It is r
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41318, '好吧，兵来将挡。先看这一页，看看上面写了什么……「欲明此经文，须献土与火之心于我。取出之热，将揭示你所求之知。」这些阿佐萨可真爱打哑谜。我只能猜，但我相信这情形和之前差不多：只有备齐相应的材料，才能解开这本魔典的秘密。$B$B土与火之心……这必定是指强大元素生物的烈焰之核与熔岩之核。取出之热……或许就是火焰精华？对，一定是这样！$B$B$N，你知道该做什么。我在这儿等你把材料带来，同时我也会尽力琢磨这本“非凡之书”。') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- Okay, we got to roll with the punches. Lets work with this page first and see whats writte
INSERT INTO `locales_quest` (`entry`, `Details_loc4`) VALUES (41319, '我越读——不如说越是读不出——就越觉得这些典籍的种种玄机，不过是某个鼻涕虫地精想快点捞钱的把戏。两页可怜巴巴的纸上写着东西，而这一页上甚至只有一句话！「以结晶之血导引日光。」这到底是想说……等等！我灵光一闪！$B$B<凡兹翻找着自己的行李，抽出一张图纸。>$B$B这是一件我始终没做成的珠宝透镜的设计图。它能把光线聚成一道极具威力的射线，用来在金属上雕刻。它需要非常特定的材料——这就轮到你出场了。「结晶之血」一定是指极难得的山中之血，产自黑石山深处。我还需要透镜的框架，黑石深渊的菲诺斯·暗脉据说拥有一块连山中最炽热的高温都损不坏的透镜。把这两样带来，我就能鼓捣出一件工具来破解这一页！') ON DUPLICATE KEY UPDATE `Details_loc4` = VALUES(`Details_loc4`);  -- The more I read - or rather DONT read - the more I believe all the mystery about these tom
