-- 服务器消息（mangos_string）
--
-- 共 271 条，只写 content_loc4（简体中文）列，这些列原本全部为空。
-- 译文遵守魔兽官方术语（例：traveler -> 旅行者，seal -> 圣印）。

SET NAMES utf8mb4;

UPDATE `mangos_string` SET `content_loc4` = '|cffff0000[事件消息]: %s|r' WHERE `entry` = 4;
UPDATE `mangos_string` SET `content_loc4` = '飞行时无法这么做。' WHERE `entry` = 18;
UPDATE `mangos_string` SET `content_loc4` = '战场中无法这么做。' WHERE `entry` = 19;
UPDATE `mangos_string` SET `content_loc4` = '目标正在飞行，你无法这么做。' WHERE `entry` = 20;
UPDATE `mangos_string` SET `content_loc4` = '%s 正在飞行，命令失败。' WHERE `entry` = 21;
UPDATE `mangos_string` SET `content_loc4` = '你没有骑乘坐骑，无法下马。' WHERE `entry` = 22;
UPDATE `mangos_string` SET `content_loc4` = '战斗中无法这么做。' WHERE `entry` = 23;
UPDATE `mangos_string` SET `content_loc4` = '你最近已经使用过了。' WHERE `entry` = 24;
UPDATE `mangos_string` SET `content_loc4` = '密码未更改（未知错误）！' WHERE `entry` = 25;
UPDATE `mangos_string` SET `content_loc4` = '密码已更改' WHERE `entry` = 26;
UPDATE `mangos_string` SET `content_loc4` = '旧密码错误' WHERE `entry` = 27;
UPDATE `mangos_string` SET `content_loc4` = '你的账号已被锁定。' WHERE `entry` = 28;
UPDATE `mangos_string` SET `content_loc4` = '你的账号已解锁。' WHERE `entry` = 29;
UPDATE `mangos_string` SET `content_loc4` = '你必须达到 %u 级才能进入。' WHERE `entry` = 49;
UPDATE `mangos_string` SET `content_loc4` = '你好！准备好接受训练了吗？' WHERE `entry` = 51;
UPDATE `mangos_string` SET `content_loc4` = '两次输入的新密码不一致' WHERE `entry` = 54;
UPDATE `mangos_string` SET `content_loc4` = '密码不能超过 16 个字符（客户端限制），密码未更改！' WHERE `entry` = 55;
UPDATE `mangos_string` SET `content_loc4` = '你现在无法使用脱困命令。' WHERE `entry` = 67;
UPDATE `mangos_string` SET `content_loc4` = '脱困功能已激活。增益效果结束后你将死亡。\n请勿进入战斗或施放法术，否则将被取消。\n请注意，该命令的每一次使用都会被记录。' WHERE `entry` = 68;
UPDATE `mangos_string` SET `content_loc4` = '脱困功能已成功激活。\n你已被传送到最近的墓地。\n请注意，该命令的每一次使用都会被记录。' WHERE `entry` = 69;
UPDATE `mangos_string` SET `content_loc4` = '队伍领袖尝试重置你所在的副本。请离开副本区域，以便其完成重置。' WHERE `entry` = 70;
UPDATE `mangos_string` SET `content_loc4` = '你收到一条来自游戏管理员的通告：%s' WHERE `entry` = 283;
UPDATE `mangos_string` SET `content_loc4` = '你的聊天功能已被禁用 %u 分钟。' WHERE `entry` = 300;
UPDATE `mangos_string` SET `content_loc4` = '你已禁用 %s 的聊天功能 %u 分钟。' WHERE `entry` = 301;
UPDATE `mangos_string` SET `content_loc4` = '该玩家的聊天功能已处于启用状态。' WHERE `entry` = 302;
UPDATE `mangos_string` SET `content_loc4` = '你的聊天功能已恢复。' WHERE `entry` = 303;
UPDATE `mangos_string` SET `content_loc4` = '你已恢复 %s 的聊天功能。' WHERE `entry` = 304;
UPDATE `mangos_string` SET `content_loc4` = '仇恨' WHERE `entry` = 318;
UPDATE `mangos_string` SET `content_loc4` = '敌对' WHERE `entry` = 319;
UPDATE `mangos_string` SET `content_loc4` = '冷淡' WHERE `entry` = 320;
UPDATE `mangos_string` SET `content_loc4` = '中立' WHERE `entry` = 321;
UPDATE `mangos_string` SET `content_loc4` = '友好' WHERE `entry` = 322;
UPDATE `mangos_string` SET `content_loc4` = '尊敬' WHERE `entry` = 323;
UPDATE `mangos_string` SET `content_loc4` = '崇敬' WHERE `entry` = 324;
UPDATE `mangos_string` SET `content_loc4` = '崇拜' WHERE `entry` = 325;
UPDATE `mangos_string` SET `content_loc4` = '该生物（编号 %u）无法被驯服。' WHERE `entry` = 343;
UPDATE `mangos_string` SET `content_loc4` = '你已经拥有宠物了。' WHERE `entry` = 344;
UPDATE `mangos_string` SET `content_loc4` = '%s 已被封禁，时长 %s。原因：%s。' WHERE `entry` = 408;
UPDATE `mangos_string` SET `content_loc4` = '%s 已被永久封禁，操作者：%s。' WHERE `entry` = 409;
UPDATE `mangos_string` SET `content_loc4` = '你学会了许多法术和技能。' WHERE `entry` = 429;
UPDATE `mangos_string` SET `content_loc4` = '你学会了本职业的所有法术。' WHERE `entry` = 430;
UPDATE `mangos_string` SET `content_loc4` = '你学会了本职业的所有天赋。' WHERE `entry` = 431;
UPDATE `mangos_string` SET `content_loc4` = '你学会了所有语言。' WHERE `entry` = 432;
UPDATE `mangos_string` SET `content_loc4` = '你学会了所有商业技能和配方。' WHERE `entry` = 433;
UPDATE `mangos_string` SET `content_loc4` = '找不到“%s”' WHERE `entry` = 434;
UPDATE `mangos_string` SET `content_loc4` = '物品编号无效：%u' WHERE `entry` = 435;
UPDATE `mangos_string` SET `content_loc4` = '未找到物品！' WHERE `entry` = 436;
UPDATE `mangos_string` SET `content_loc4` = '物件编号无效：%u' WHERE `entry` = 437;
UPDATE `mangos_string` SET `content_loc4` = '生物编号无效：%u' WHERE `entry` = 440;
UPDATE `mangos_string` SET `content_loc4` = '未找到区域！' WHERE `entry` = 442;
UPDATE `mangos_string` SET `content_loc4` = '未找到套装！' WHERE `entry` = 443;
UPDATE `mangos_string` SET `content_loc4` = '未找到技能！' WHERE `entry` = 444;
UPDATE `mangos_string` SET `content_loc4` = '未找到法术！' WHERE `entry` = 445;
UPDATE `mangos_string` SET `content_loc4` = '未找到任务！' WHERE `entry` = 446;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物！' WHERE `entry` = 447;
UPDATE `mangos_string` SET `content_loc4` = '未找到物件！' WHERE `entry` = 448;
UPDATE `mangos_string` SET `content_loc4` = '你已发现本方阵营的所有飞行点。' WHERE `entry` = 453;
UPDATE `mangos_string` SET `content_loc4` = '未找到任务 %u。' WHERE `entry` = 471;
UPDATE `mangos_string` SET `content_loc4` = '任务已移除。' WHERE `entry` = 473;
UPDATE `mangos_string` SET `content_loc4` = '联盟获胜！' WHERE `entry` = 600;
UPDATE `mangos_string` SET `content_loc4` = '部落获胜！' WHERE `entry` = 601;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗将在 1 分钟后开始。' WHERE `entry` = 602;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 603;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗，开始吧！' WHERE `entry` = 604;
UPDATE `mangos_string` SET `content_loc4` = '$n 夺取了部落的战旗！' WHERE `entry` = 605;
UPDATE `mangos_string` SET `content_loc4` = '$n 夺取了联盟的战旗！' WHERE `entry` = 606;
UPDATE `mangos_string` SET `content_loc4` = '部落的战旗被 $n 丢弃了！' WHERE `entry` = 607;
UPDATE `mangos_string` SET `content_loc4` = '联盟的战旗被 $n 丢弃了！' WHERE `entry` = 608;
UPDATE `mangos_string` SET `content_loc4` = '$n 将联盟的战旗送回了基地！' WHERE `entry` = 609;
UPDATE `mangos_string` SET `content_loc4` = '$n 将部落的战旗送回了基地！' WHERE `entry` = 610;
UPDATE `mangos_string` SET `content_loc4` = '$n 拾起了部落的战旗！' WHERE `entry` = 611;
UPDATE `mangos_string` SET `content_loc4` = '$n 拾起了联盟的战旗！' WHERE `entry` = 612;
UPDATE `mangos_string` SET `content_loc4` = '双方战旗已回到各自基地。' WHERE `entry` = 613;
UPDATE `mangos_string` SET `content_loc4` = '联盟的战旗已回到基地。' WHERE `entry` = 614;
UPDATE `mangos_string` SET `content_loc4` = '部落的战旗已回到基地。' WHERE `entry` = 615;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗将在 1 分钟后开始。' WHERE `entry` = 636;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗将在 30 秒后开始。' WHERE `entry` = 637;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗已经开始！' WHERE `entry` = 638;
UPDATE `mangos_string` SET `content_loc4` = '联盟' WHERE `entry` = 650;
UPDATE `mangos_string` SET `content_loc4` = '部落' WHERE `entry` = 651;
UPDATE `mangos_string` SET `content_loc4` = '兽栏' WHERE `entry` = 652;
UPDATE `mangos_string` SET `content_loc4` = '铁匠铺' WHERE `entry` = 653;
UPDATE `mangos_string` SET `content_loc4` = '农场' WHERE `entry` = 654;
UPDATE `mangos_string` SET `content_loc4` = '伐木场' WHERE `entry` = 655;
UPDATE `mangos_string` SET `content_loc4` = '矿洞' WHERE `entry` = 656;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s' WHERE `entry` = 657;
UPDATE `mangos_string` SET `content_loc4` = '$n 防守住了 %s' WHERE `entry` = 658;
UPDATE `mangos_string` SET `content_loc4` = '$n 袭击了 %s' WHERE `entry` = 659;
UPDATE `mangos_string` SET `content_loc4` = '$n 宣称占领了 %s！若无人争夺，%s 将在 1 分钟后控制它！' WHERE `entry` = 660;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗将在 1 分钟后开始。' WHERE `entry` = 661;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 662;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗已经开始！' WHERE `entry` = 663;
UPDATE `mangos_string` SET `content_loc4` = '联盟已收集到 $1776W 资源，胜利在望！' WHERE `entry` = 664;
UPDATE `mangos_string` SET `content_loc4` = '部落已收集到 $1777W 资源，胜利在望！' WHERE `entry` = 665;
UPDATE `mangos_string` SET `content_loc4` = '在你最近于 %s 的战斗结束后，我们未能成功将荣誉标记发放给你。随信附上当时未能送达的荣誉标记。感谢你在 %s 的奋战！' WHERE `entry` = 666;
UPDATE `mangos_string` SET `content_loc4` = '亲爱的玩家：\n\n请收下随信附上的物品。该物品此前因不应在当前版本中获取而被从你的角色身上移除，但我们的技术人员已确认，现在你可以重新拥有它！' WHERE `entry` = 699;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 1 分钟后开始！' WHERE `entry` = 701;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 30 秒后开始！' WHERE `entry` = 702;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 15 秒后开始！' WHERE `entry` = 703;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗已经开始！' WHERE `entry` = 704;
UPDATE `mangos_string` SET `content_loc4` = '你必须等待 %s 才能再次发言。' WHERE `entry` = 705;
UPDATE `mangos_string` SET `content_loc4` = '该物品在装备或放入背包时出现了问题。' WHERE `entry` = 706;
UPDATE `mangos_string` SET `content_loc4` = '%s 希望不被打扰，无法接收密语：%s' WHERE `entry` = 707;
UPDATE `mangos_string` SET `content_loc4` = '%s 处于暂离状态：%s' WHERE `entry` = 708;
UPDATE `mangos_string` SET `content_loc4` = '请勿打扰' WHERE `entry` = 709;
UPDATE `mangos_string` SET `content_loc4` = '暂离' WHERE `entry` = 710;
UPDATE `mangos_string` SET `content_loc4` = '%s 的队列状态（等级 %u 至 %u）\n联盟排队人数：%u（至少还需 %u 人）\n部落排队人数：%u（至少还需 %u 人）' WHERE `entry` = 711;
UPDATE `mangos_string` SET `content_loc4` = '|cffff0000[战场]:|r %s [%u-%u] 联盟: %u/%u，部落: %u/%u|r' WHERE `entry` = 712;
UPDATE `mangos_string` SET `content_loc4` = '你未达到该战场的等级要求' WHERE `entry` = 715;
UPDATE `mangos_string` SET `content_loc4` = '%s [%u-%u] 已开始！' WHERE `entry` = 717;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍人数超过该战场上限，请重新组队后再加入。' WHERE `entry` = 720;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有离线成员，请先将其移出再加入。' WHERE `entry` = 727;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有敌对阵营的玩家，无法以队伍形式加入战场。' WHERE `entry` = 728;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有属于不同战场等级的玩家，无法以队伍形式加入。' WHERE `entry` = 729;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中已有人在该战场队列中，其必须先离开才能以队伍形式加入。' WHERE `entry` = 730;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有人带有逃兵状态，无法以队伍形式加入。' WHERE `entry` = 731;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中已有人同时处于三个战场队列中，无法以队伍形式加入。' WHERE `entry` = 732;
UPDATE `mangos_string` SET `content_loc4` = '你无法传送到战场地图。' WHERE `entry` = 733;
UPDATE `mangos_string` SET `content_loc4` = '你无法将玩家召唤到战场或竞技场地图。' WHERE `entry` = 734;
UPDATE `mangos_string` SET `content_loc4` = '你必须开启 GM 模式才能传送到战场中的玩家身边。' WHERE `entry` = 735;
UPDATE `mangos_string` SET `content_loc4` = '你无法从一个战场传送到另一个战场。请先离开当前战场。' WHERE `entry` = 736;
UPDATE `mangos_string` SET `content_loc4` = '玩家人数不足。本场游戏将在 %u 分钟后关闭。' WHERE `entry` = 750;
UPDATE `mangos_string` SET `content_loc4` = '玩家人数不足。本场游戏将在 %u 秒后关闭。' WHERE `entry` = 751;
UPDATE `mangos_string` SET `content_loc4` = '只有联盟可以使用该传送门' WHERE `entry` = 752;
UPDATE `mangos_string` SET `content_loc4` = '只有部落可以使用该传送门' WHERE `entry` = 753;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 摧毁了！' WHERE `entry` = 759;
UPDATE `mangos_string` SET `content_loc4` = '%s 正遭受攻击！若不加以阻止，%s 将摧毁它！' WHERE `entry` = 760;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 761;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 762;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 763;
UPDATE `mangos_string` SET `content_loc4` = '%s 正遭受攻击！若不加以阻止，%s 将占领它！' WHERE `entry` = 764;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s！其补给将被用于增援！' WHERE `entry` = 765;
UPDATE `mangos_string` SET `content_loc4` = '深铁矿洞' WHERE `entry` = 766;
UPDATE `mangos_string` SET `content_loc4` = '冷齿矿洞' WHERE `entry` = 767;
UPDATE `mangos_string` SET `content_loc4` = '雷矛急救站' WHERE `entry` = 768;
UPDATE `mangos_string` SET `content_loc4` = '丹巴达尔南部碉堡' WHERE `entry` = 769;
UPDATE `mangos_string` SET `content_loc4` = '丹巴达尔北部碉堡' WHERE `entry` = 770;
UPDATE `mangos_string` SET `content_loc4` = '雷矛墓地' WHERE `entry` = 771;
UPDATE `mangos_string` SET `content_loc4` = '冰翼碉堡' WHERE `entry` = 772;
UPDATE `mangos_string` SET `content_loc4` = '石炉墓地' WHERE `entry` = 773;
UPDATE `mangos_string` SET `content_loc4` = '石炉碉堡' WHERE `entry` = 774;
UPDATE `mangos_string` SET `content_loc4` = '雪落墓地' WHERE `entry` = 775;
UPDATE `mangos_string` SET `content_loc4` = '冰血哨塔' WHERE `entry` = 776;
UPDATE `mangos_string` SET `content_loc4` = '冰血墓地' WHERE `entry` = 777;
UPDATE `mangos_string` SET `content_loc4` = '哨塔高地' WHERE `entry` = 778;
UPDATE `mangos_string` SET `content_loc4` = '霜狼墓地' WHERE `entry` = 779;
UPDATE `mangos_string` SET `content_loc4` = '霜狼东部哨塔' WHERE `entry` = 780;
UPDATE `mangos_string` SET `content_loc4` = '霜狼西部哨塔' WHERE `entry` = 781;
UPDATE `mangos_string` SET `content_loc4` = '霜狼救济所' WHERE `entry` = 782;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗将在 1 分钟后开始。' WHERE `entry` = 784;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 785;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗已经开始！' WHERE `entry` = 786;
UPDATE `mangos_string` SET `content_loc4` = '联盟的增援即将耗尽！' WHERE `entry` = 787;
UPDATE `mangos_string` SET `content_loc4` = '部落的增援即将耗尽！' WHERE `entry` = 788;
UPDATE `mangos_string` SET `content_loc4` = '霜狼将军已阵亡！' WHERE `entry` = 789;
UPDATE `mangos_string` SET `content_loc4` = '雷矛将军已阵亡！' WHERE `entry` = 790;
UPDATE `mangos_string` SET `content_loc4` = '进攻的时刻到了！为了部落！' WHERE `entry` = 792;
UPDATE `mangos_string` SET `content_loc4` = '振作起来，联盟！把这些恶徒赶出奥特兰克山谷！' WHERE `entry` = 793;
UPDATE `mangos_string` SET `content_loc4` = '你的金币不足' WHERE `entry` = 801;
UPDATE `mangos_string` SET `content_loc4` = '你没有足够的空余栏位' WHERE `entry` = 802;
UPDATE `mangos_string` SET `content_loc4` = '你的交易对象没有足够的空余背包栏位' WHERE `entry` = 803;
UPDATE `mangos_string` SET `content_loc4` = '你没有执行该操作的权限' WHERE `entry` = 804;
UPDATE `mangos_string` SET `content_loc4` = '未知语言' WHERE `entry` = 805;
UPDATE `mangos_string` SET `content_loc4` = '你不懂该语言' WHERE `entry` = 806;
UPDATE `mangos_string` SET `content_loc4` = '请提供角色名' WHERE `entry` = 807;
UPDATE `mangos_string` SET `content_loc4` = '未找到玩家 %s，或该玩家不在线' WHERE `entry` = 808;
UPDATE `mangos_string` SET `content_loc4` = '未找到角色 %s 所属的账号' WHERE `entry` = 809;
UPDATE `mangos_string` SET `content_loc4` = '公会会长' WHERE `entry` = 811;
UPDATE `mangos_string` SET `content_loc4` = '官员' WHERE `entry` = 812;
UPDATE `mangos_string` SET `content_loc4` = '老兵' WHERE `entry` = 813;
UPDATE `mangos_string` SET `content_loc4` = '成员' WHERE `entry` = 814;
UPDATE `mangos_string` SET `content_loc4` = '新成员' WHERE `entry` = 815;
UPDATE `mangos_string` SET `content_loc4` = '列兵' WHERE `entry` = 1400;
UPDATE `mangos_string` SET `content_loc4` = '下士' WHERE `entry` = 1401;
UPDATE `mangos_string` SET `content_loc4` = '中士' WHERE `entry` = 1402;
UPDATE `mangos_string` SET `content_loc4` = '军士长' WHERE `entry` = 1403;
UPDATE `mangos_string` SET `content_loc4` = '士官长' WHERE `entry` = 1404;
UPDATE `mangos_string` SET `content_loc4` = '骑士' WHERE `entry` = 1405;
UPDATE `mangos_string` SET `content_loc4` = '骑士中尉' WHERE `entry` = 1406;
UPDATE `mangos_string` SET `content_loc4` = '骑士队长' WHERE `entry` = 1407;
UPDATE `mangos_string` SET `content_loc4` = '骑士统领' WHERE `entry` = 1408;
UPDATE `mangos_string` SET `content_loc4` = '护卫骑士' WHERE `entry` = 1409;
UPDATE `mangos_string` SET `content_loc4` = '司令' WHERE `entry` = 1410;
UPDATE `mangos_string` SET `content_loc4` = '统帅' WHERE `entry` = 1411;
UPDATE `mangos_string` SET `content_loc4` = '司令统帅' WHERE `entry` = 1412;
UPDATE `mangos_string` SET `content_loc4` = '大统帅' WHERE `entry` = 1413;
UPDATE `mangos_string` SET `content_loc4` = '侦察兵' WHERE `entry` = 1414;
UPDATE `mangos_string` SET `content_loc4` = '步兵' WHERE `entry` = 1415;
UPDATE `mangos_string` SET `content_loc4` = '中士' WHERE `entry` = 1416;
UPDATE `mangos_string` SET `content_loc4` = '高阶军士' WHERE `entry` = 1417;
UPDATE `mangos_string` SET `content_loc4` = '一等军士长' WHERE `entry` = 1418;
UPDATE `mangos_string` SET `content_loc4` = '石头守卫' WHERE `entry` = 1419;
UPDATE `mangos_string` SET `content_loc4` = '血卫士' WHERE `entry` = 1420;
UPDATE `mangos_string` SET `content_loc4` = '军团士兵' WHERE `entry` = 1421;
UPDATE `mangos_string` SET `content_loc4` = '百夫长' WHERE `entry` = 1422;
UPDATE `mangos_string` SET `content_loc4` = '勇士' WHERE `entry` = 1423;
UPDATE `mangos_string` SET `content_loc4` = '中将' WHERE `entry` = 1424;
UPDATE `mangos_string` SET `content_loc4` = '将军' WHERE `entry` = 1425;
UPDATE `mangos_string` SET `content_loc4` = '督军' WHERE `entry` = 1426;
UPDATE `mangos_string` SET `content_loc4` = '高阶督军' WHERE `entry` = 1427;
UPDATE `mangos_string` SET `content_loc4` = '游戏管理员' WHERE `entry` = 1428;
UPDATE `mangos_string` SET `content_loc4` = '无军衔' WHERE `entry` = 1429;
UPDATE `mangos_string` SET `content_loc4` = '被唾弃 ' WHERE `entry` = 1430;
UPDATE `mangos_string` SET `content_loc4` = '被放逐 ' WHERE `entry` = 1431;
UPDATE `mangos_string` SET `content_loc4` = '亡命者 ' WHERE `entry` = 1432;
UPDATE `mangos_string` SET `content_loc4` = '贱民 ' WHERE `entry` = 1433;
UPDATE `mangos_string` SET `content_loc4` = '玩家：%s - %s（军衔 %u）' WHERE `entry` = 1434;
UPDATE `mangos_string` SET `content_loc4` = '今日：[荣誉击杀：|c0000ff00%u|r] [非荣誉击杀：|c00ff0000%u|r]' WHERE `entry` = 1435;
UPDATE `mangos_string` SET `content_loc4` = '昨日：[击杀：|c0000ff00%u|r] [荣誉：%u]' WHERE `entry` = 1436;
UPDATE `mangos_string` SET `content_loc4` = '本周：[击杀：|c0000ff00%u|r] [荣誉：%u]' WHERE `entry` = 1437;
UPDATE `mangos_string` SET `content_loc4` = '上周：[击杀：|c0000ff00%u|r] [荣誉：%u] [排名：%u]' WHERE `entry` = 1438;
UPDATE `mangos_string` SET `content_loc4` = '生涯：[军衔分数：|c0000ff00%f|r] [荣誉击杀：|c0000ff00%u|r] [非荣誉击杀：|c00ff0000%u|r] [最高军衔 %u：%s]' WHERE `entry` = 1439;
UPDATE `mangos_string` SET `content_loc4` = '我想看看你的货物。' WHERE `entry` = 2000;
UPDATE `mangos_string` SET `content_loc4` = '训练我！' WHERE `entry` = 2001;
UPDATE `mangos_string` SET `content_loc4` = '%s 试图因恐惧而逃跑！' WHERE `entry` = 5030;
UPDATE `mangos_string` SET `content_loc4` = '%s 已复活（在线）' WHERE `entry` = 5031;
UPDATE `mangos_string` SET `content_loc4` = '%s 已复活（离线）' WHERE `entry` = 5032;
UPDATE `mangos_string` SET `content_loc4` = '|cffffff00[|c1f40af20GM 公告，发布者|r |cffff0000%s|cffffff00]:|r |c1111ff00 %s|r' WHERE `entry` = 6615;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了北地哨塔！' WHERE `entry` = 10033;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了北地哨塔！' WHERE `entry` = 10034;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了东墙哨塔！' WHERE `entry` = 10035;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了东墙哨塔！' WHERE `entry` = 10036;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了皇冠哨塔！' WHERE `entry` = 10037;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了皇冠哨塔！' WHERE `entry` = 10038;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了病木林哨塔！' WHERE `entry` = 10039;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了病木林哨塔！' WHERE `entry` = 10040;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了北地哨塔！' WHERE `entry` = 10041;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了北地哨塔！' WHERE `entry` = 10042;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了东墙哨塔！' WHERE `entry` = 10043;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了东墙哨塔！' WHERE `entry` = 10044;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了皇冠哨塔！' WHERE `entry` = 10045;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了皇冠哨塔！' WHERE `entry` = 10046;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了病木林哨塔！' WHERE `entry` = 10047;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了病木林哨塔！' WHERE `entry` = 10048;
UPDATE `mangos_string` SET `content_loc4` = '部落已收集 200 份异种蝎壳！' WHERE `entry` = 10049;
UPDATE `mangos_string` SET `content_loc4` = '联盟已收集 200 份异种蝎壳！' WHERE `entry` = 10050;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗将在 1 分钟后开始。' WHERE `entry` = 10051;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 10052;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗，开始吧！' WHERE `entry` = 10053;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s' WHERE `entry` = 10054;
UPDATE `mangos_string` SET `content_loc4` = '$n 防守住了 %s' WHERE `entry` = 10055;
UPDATE `mangos_string` SET `content_loc4` = '$n 袭击了 %s' WHERE `entry` = 10056;
UPDATE `mangos_string` SET `content_loc4` = '$n 宣称占领了 %s！若无人争夺，%s 将在 1 分钟后控制它！' WHERE `entry` = 10057;
UPDATE `mangos_string` SET `content_loc4` = '往日的宿怨导致了你的失败，真是可惜……' WHERE `entry` = 10058;
UPDATE `mangos_string` SET `content_loc4` = '时间流已被改变，我们无法确定是哪些事件导致了偏移，如今它将产生难以预料的影响。' WHERE `entry` = 10059;
UPDATE `mangos_string` SET `content_loc4` = '决战在即，英雄们。加入战斗，在你的敌人中找出潜伏的永恒龙军团密探！' WHERE `entry` = 10060;
UPDATE `mangos_string` SET `content_loc4` = '林荫郡塔' WHERE `entry` = 10061;
UPDATE `mangos_string` SET `content_loc4` = '戈尔德雷加塔' WHERE `entry` = 10062;
UPDATE `mangos_string` SET `content_loc4` = '英勇堡' WHERE `entry` = 10063;
UPDATE `mangos_string` SET `content_loc4` = '加入英文社区频道（/join WorldEN）与其他玩家交流！' WHERE `entry` = 11011;
UPDATE `mangos_string` SET `content_loc4` = '使用命令 “.go warsong”、“.go arathi” 和 “.go alterac” 可以从任何地方加入战场！' WHERE `entry` = 11012;
UPDATE `mangos_string` SET `content_loc4` = '为帮助服务器人口增长，请发起拉新活动！提供 60 级 NPC，支持从其他服务器导入角色，欢迎关注我们的 Facebook！' WHERE `entry` = 11013;
UPDATE `mangos_string` SET `content_loc4` = '服务器将于 8 月 19 日停机以进行国际版发布，详情请见论坛' WHERE `entry` = 11014;
UPDATE `mangos_string` SET `content_loc4` = 'Nostalrius 是一个 PVP 与 PVE 服务器。但请注意，试图恶心其他玩家的行为将受到惩罚。' WHERE `entry` = 11015;
UPDATE `mangos_string` SET `content_loc4` = '赏金猎人系统已开放。联系游戏管理员，为某人开出你的悬赏价，详情请见论坛的活动版块。' WHERE `entry` = 11016;
UPDATE `mangos_string` SET `content_loc4` = '这是 Turtle-WoW 1.18.1 的非官方延续版本' WHERE `entry` = 50009;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：在官方服上就是这么运作的……|r' WHERE `entry` = 50200;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：术士太强了！|r' WHERE `entry` = 50201;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：火抗被高估了。|r' WHERE `entry` = 50202;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：你以为你想，其实你不想。|r' WHERE `entry` = 50203;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：那边的草更绿……|r' WHERE `entry` = 50204;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：防护骑也能当坦克！|r' WHERE `entry` = 50205;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：谁也不会只拉一只鱼人！|r' WHERE `entry` = 50206;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：神圣抗性什么的……|r' WHERE `entry` = 50207;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：在 Nostalrius 上一切都是正常的。|r' WHERE `entry` = 50208;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：你知道侏儒做的鞋最好吗？难的是把脚塞进他们那张小嘴里。|r' WHERE `entry` = 50209;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：咚咚咚。谁啊？是个侏儒，我够不着门铃！|r' WHERE `entry` = 50210;
UPDATE `mangos_string` SET `content_loc4` = '悲剧发生了。硬核角色 %s（等级 %u）%s。愿这份牺牲不被遗忘。' WHERE `entry` = 50300;
UPDATE `mangos_string` SET `content_loc4` = '%s 在硬核模式下达到了 %u 级！随着其向不朽攀登，荣耀日益增长！然而，所面临的危险也与日俱增。' WHERE `entry` = 50301;
UPDATE `mangos_string` SET `content_loc4` = '%s 超越了死亡，在硬核模式下一次未死地达到了 60 级！从今往后，%s 将被称为不朽者！' WHERE `entry` = 50302;
UPDATE `mangos_string` SET `content_loc4` = '%s 完成了 2800 个任务，如今被称为求知者，激励着同道冒险者去探索未知！' WHERE `entry` = 50305;

