-- 服务器消息（mangos_string）
--
-- 共 946 条，只写 content_loc4（简体中文）列，这些列原本全部为空。
-- 译文遵守魔兽官方术语（例：traveler -> 旅行者，seal -> 圣印）。

SET NAMES utf8mb4;

UPDATE `mangos_string` SET `content_loc4` = '|cffff0000[事件消息]: %s|r' WHERE `entry` = 4;
UPDATE `mangos_string` SET `content_loc4` = '飞行时无法这么做。' WHERE `entry` = 18;
UPDATE `mangos_string` SET `content_loc4` = '战场中无法这么做。' WHERE `entry` = 19;
UPDATE `mangos_string` SET `content_loc4` = '目标正在飞行，你无法这么做。' WHERE `entry` = 20;
UPDATE `mangos_string` SET `content_loc4` = '%s 正在飞行，命令失败。' WHERE `entry` = 21;
UPDATE `mangos_string` SET `content_loc4` = '你没有骑乘坐骑，无法下马。' WHERE `entry` = 22;
UPDATE `mangos_string` SET `content_loc4` = '战斗中无法这么做。' WHERE `entry` = 23;
UPDATE `mangos_string` SET `content_loc4` = '你最近已经使用过了。' WHERE `entry` = 24;
UPDATE `mangos_string` SET `content_loc4` = '密码未更改（未知错误）！' WHERE `entry` = 25;
UPDATE `mangos_string` SET `content_loc4` = '密码已更改' WHERE `entry` = 26;
UPDATE `mangos_string` SET `content_loc4` = '旧密码错误' WHERE `entry` = 27;
UPDATE `mangos_string` SET `content_loc4` = '你的账号已被锁定。' WHERE `entry` = 28;
UPDATE `mangos_string` SET `content_loc4` = '你的账号已解锁。' WHERE `entry` = 29;
UPDATE `mangos_string` SET `content_loc4` = '你必须达到 %u 级才能进入。' WHERE `entry` = 49;
UPDATE `mangos_string` SET `content_loc4` = '你好！准备好接受训练了吗？' WHERE `entry` = 51;
UPDATE `mangos_string` SET `content_loc4` = '两次输入的新密码不一致' WHERE `entry` = 54;
UPDATE `mangos_string` SET `content_loc4` = '密码不能超过 16 个字符（客户端限制），密码未更改！' WHERE `entry` = 55;
UPDATE `mangos_string` SET `content_loc4` = '你现在无法使用脱困命令。' WHERE `entry` = 67;
UPDATE `mangos_string` SET `content_loc4` = '脱困功能已激活。增益效果结束后你将死亡。\n请勿进入战斗或施放法术，否则将被取消。\n请注意，该命令的每一次使用都会被记录。' WHERE `entry` = 68;
UPDATE `mangos_string` SET `content_loc4` = '脱困功能已成功激活。\n你已被传送到最近的墓地。\n请注意，该命令的每一次使用都会被记录。' WHERE `entry` = 69;
UPDATE `mangos_string` SET `content_loc4` = '队伍领袖尝试重置你所在的副本。请离开副本区域，以便其完成重置。' WHERE `entry` = 70;
UPDATE `mangos_string` SET `content_loc4` = '你收到一条来自游戏管理员的通告：%s' WHERE `entry` = 283;
UPDATE `mangos_string` SET `content_loc4` = '你的聊天功能已被禁用 %u 分钟。' WHERE `entry` = 300;
UPDATE `mangos_string` SET `content_loc4` = '你已禁用 %s 的聊天功能 %u 分钟。' WHERE `entry` = 301;
UPDATE `mangos_string` SET `content_loc4` = '该玩家的聊天功能已处于启用状态。' WHERE `entry` = 302;
UPDATE `mangos_string` SET `content_loc4` = '你的聊天功能已恢复。' WHERE `entry` = 303;
UPDATE `mangos_string` SET `content_loc4` = '你已恢复 %s 的聊天功能。' WHERE `entry` = 304;
UPDATE `mangos_string` SET `content_loc4` = '仇恨' WHERE `entry` = 318;
UPDATE `mangos_string` SET `content_loc4` = '敌对' WHERE `entry` = 319;
UPDATE `mangos_string` SET `content_loc4` = '冷淡' WHERE `entry` = 320;
UPDATE `mangos_string` SET `content_loc4` = '中立' WHERE `entry` = 321;
UPDATE `mangos_string` SET `content_loc4` = '友好' WHERE `entry` = 322;
UPDATE `mangos_string` SET `content_loc4` = '尊敬' WHERE `entry` = 323;
UPDATE `mangos_string` SET `content_loc4` = '崇敬' WHERE `entry` = 324;
UPDATE `mangos_string` SET `content_loc4` = '崇拜' WHERE `entry` = 325;
UPDATE `mangos_string` SET `content_loc4` = '该生物（编号 %u）无法被驯服。' WHERE `entry` = 343;
UPDATE `mangos_string` SET `content_loc4` = '你已经拥有宠物了。' WHERE `entry` = 344;
UPDATE `mangos_string` SET `content_loc4` = '%s 已被封禁，时长 %s。原因：%s。' WHERE `entry` = 408;
UPDATE `mangos_string` SET `content_loc4` = '%s 已被永久封禁，操作者：%s。' WHERE `entry` = 409;
UPDATE `mangos_string` SET `content_loc4` = '你学会了许多法术和技能。' WHERE `entry` = 429;
UPDATE `mangos_string` SET `content_loc4` = '你学会了本职业的所有法术。' WHERE `entry` = 430;
UPDATE `mangos_string` SET `content_loc4` = '你学会了本职业的所有天赋。' WHERE `entry` = 431;
UPDATE `mangos_string` SET `content_loc4` = '你学会了所有语言。' WHERE `entry` = 432;
UPDATE `mangos_string` SET `content_loc4` = '你学会了所有商业技能和配方。' WHERE `entry` = 433;
UPDATE `mangos_string` SET `content_loc4` = '找不到“%s”' WHERE `entry` = 434;
UPDATE `mangos_string` SET `content_loc4` = '物品编号无效：%u' WHERE `entry` = 435;
UPDATE `mangos_string` SET `content_loc4` = '未找到物品！' WHERE `entry` = 436;
UPDATE `mangos_string` SET `content_loc4` = '物件编号无效：%u' WHERE `entry` = 437;
UPDATE `mangos_string` SET `content_loc4` = '生物编号无效：%u' WHERE `entry` = 440;
UPDATE `mangos_string` SET `content_loc4` = '未找到区域！' WHERE `entry` = 442;
UPDATE `mangos_string` SET `content_loc4` = '未找到套装！' WHERE `entry` = 443;
UPDATE `mangos_string` SET `content_loc4` = '未找到技能！' WHERE `entry` = 444;
UPDATE `mangos_string` SET `content_loc4` = '未找到法术！' WHERE `entry` = 445;
UPDATE `mangos_string` SET `content_loc4` = '未找到任务！' WHERE `entry` = 446;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物！' WHERE `entry` = 447;
UPDATE `mangos_string` SET `content_loc4` = '未找到物件！' WHERE `entry` = 448;
UPDATE `mangos_string` SET `content_loc4` = '你已发现本方阵营的所有飞行点。' WHERE `entry` = 453;
UPDATE `mangos_string` SET `content_loc4` = '未找到任务 %u。' WHERE `entry` = 471;
UPDATE `mangos_string` SET `content_loc4` = '任务已移除。' WHERE `entry` = 473;
UPDATE `mangos_string` SET `content_loc4` = '联盟获胜！' WHERE `entry` = 600;
UPDATE `mangos_string` SET `content_loc4` = '部落获胜！' WHERE `entry` = 601;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗将在 1 分钟后开始。' WHERE `entry` = 602;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 603;
UPDATE `mangos_string` SET `content_loc4` = '战歌峡谷的战斗，开始吧！' WHERE `entry` = 604;
UPDATE `mangos_string` SET `content_loc4` = '$n 夺取了部落的战旗！' WHERE `entry` = 605;
UPDATE `mangos_string` SET `content_loc4` = '$n 夺取了联盟的战旗！' WHERE `entry` = 606;
UPDATE `mangos_string` SET `content_loc4` = '部落的战旗被 $n 丢弃了！' WHERE `entry` = 607;
UPDATE `mangos_string` SET `content_loc4` = '联盟的战旗被 $n 丢弃了！' WHERE `entry` = 608;
UPDATE `mangos_string` SET `content_loc4` = '$n 将联盟的战旗送回了基地！' WHERE `entry` = 609;
UPDATE `mangos_string` SET `content_loc4` = '$n 将部落的战旗送回了基地！' WHERE `entry` = 610;
UPDATE `mangos_string` SET `content_loc4` = '$n 拾起了部落的战旗！' WHERE `entry` = 611;
UPDATE `mangos_string` SET `content_loc4` = '$n 拾起了联盟的战旗！' WHERE `entry` = 612;
UPDATE `mangos_string` SET `content_loc4` = '双方战旗已回到各自基地。' WHERE `entry` = 613;
UPDATE `mangos_string` SET `content_loc4` = '联盟的战旗已回到基地。' WHERE `entry` = 614;
UPDATE `mangos_string` SET `content_loc4` = '部落的战旗已回到基地。' WHERE `entry` = 615;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗将在 1 分钟后开始。' WHERE `entry` = 636;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗将在 30 秒后开始。' WHERE `entry` = 637;
UPDATE `mangos_string` SET `content_loc4` = '风暴之眼的战斗已经开始！' WHERE `entry` = 638;
UPDATE `mangos_string` SET `content_loc4` = '联盟' WHERE `entry` = 650;
UPDATE `mangos_string` SET `content_loc4` = '部落' WHERE `entry` = 651;
UPDATE `mangos_string` SET `content_loc4` = '兽栏' WHERE `entry` = 652;
UPDATE `mangos_string` SET `content_loc4` = '铁匠铺' WHERE `entry` = 653;
UPDATE `mangos_string` SET `content_loc4` = '农场' WHERE `entry` = 654;
UPDATE `mangos_string` SET `content_loc4` = '伐木场' WHERE `entry` = 655;
UPDATE `mangos_string` SET `content_loc4` = '矿洞' WHERE `entry` = 656;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s' WHERE `entry` = 657;
UPDATE `mangos_string` SET `content_loc4` = '$n 防守住了 %s' WHERE `entry` = 658;
UPDATE `mangos_string` SET `content_loc4` = '$n 袭击了 %s' WHERE `entry` = 659;
UPDATE `mangos_string` SET `content_loc4` = '$n 宣称占领了 %s！若无人争夺，%s 将在 1 分钟后控制它！' WHERE `entry` = 660;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗将在 1 分钟后开始。' WHERE `entry` = 661;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 662;
UPDATE `mangos_string` SET `content_loc4` = '阿拉希盆地的战斗已经开始！' WHERE `entry` = 663;
UPDATE `mangos_string` SET `content_loc4` = '联盟已收集到 $1776W 资源，胜利在望！' WHERE `entry` = 664;
UPDATE `mangos_string` SET `content_loc4` = '部落已收集到 $1777W 资源，胜利在望！' WHERE `entry` = 665;
UPDATE `mangos_string` SET `content_loc4` = '在你最近于 %s 的战斗结束后，我们未能成功将荣誉标记发放给你。随信附上当时未能送达的荣誉标记。感谢你在 %s 的奋战！' WHERE `entry` = 666;
UPDATE `mangos_string` SET `content_loc4` = '亲爱的玩家：\n\n请收下随信附上的物品。该物品此前因不应在当前版本中获取而被从你的角色身上移除，但我们的技术人员已确认，现在你可以重新拥有它！' WHERE `entry` = 699;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 1 分钟后开始！' WHERE `entry` = 701;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 30 秒后开始！' WHERE `entry` = 702;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗将在 15 秒后开始！' WHERE `entry` = 703;
UPDATE `mangos_string` SET `content_loc4` = '竞技场战斗已经开始！' WHERE `entry` = 704;
UPDATE `mangos_string` SET `content_loc4` = '你必须等待 %s 才能再次发言。' WHERE `entry` = 705;
UPDATE `mangos_string` SET `content_loc4` = '该物品在装备或放入背包时出现了问题。' WHERE `entry` = 706;
UPDATE `mangos_string` SET `content_loc4` = '%s 希望不被打扰，无法接收密语：%s' WHERE `entry` = 707;
UPDATE `mangos_string` SET `content_loc4` = '%s 处于暂离状态：%s' WHERE `entry` = 708;
UPDATE `mangos_string` SET `content_loc4` = '请勿打扰' WHERE `entry` = 709;
UPDATE `mangos_string` SET `content_loc4` = '暂离' WHERE `entry` = 710;
UPDATE `mangos_string` SET `content_loc4` = '%s 的队列状态（等级 %u 至 %u）\n联盟排队人数：%u（至少还需 %u 人）\n部落排队人数：%u（至少还需 %u 人）' WHERE `entry` = 711;
UPDATE `mangos_string` SET `content_loc4` = '|cffff0000[战场]:|r %s [%u-%u] 联盟: %u/%u，部落: %u/%u|r' WHERE `entry` = 712;
UPDATE `mangos_string` SET `content_loc4` = '你未达到该战场的等级要求' WHERE `entry` = 715;
UPDATE `mangos_string` SET `content_loc4` = '%s [%u-%u] 已开始！' WHERE `entry` = 717;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍人数超过该战场上限，请重新组队后再加入。' WHERE `entry` = 720;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有离线成员，请先将其移出再加入。' WHERE `entry` = 727;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有敌对阵营的玩家，无法以队伍形式加入战场。' WHERE `entry` = 728;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有属于不同战场等级的玩家，无法以队伍形式加入。' WHERE `entry` = 729;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中已有人在该战场队列中，其必须先离开才能以队伍形式加入。' WHERE `entry` = 730;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中有人带有逃兵状态，无法以队伍形式加入。' WHERE `entry` = 731;
UPDATE `mangos_string` SET `content_loc4` = '你的队伍中已有人同时处于三个战场队列中，无法以队伍形式加入。' WHERE `entry` = 732;
UPDATE `mangos_string` SET `content_loc4` = '你无法传送到战场地图。' WHERE `entry` = 733;
UPDATE `mangos_string` SET `content_loc4` = '你无法将玩家召唤到战场或竞技场地图。' WHERE `entry` = 734;
UPDATE `mangos_string` SET `content_loc4` = '你必须开启 GM 模式才能传送到战场中的玩家身边。' WHERE `entry` = 735;
UPDATE `mangos_string` SET `content_loc4` = '你无法从一个战场传送到另一个战场。请先离开当前战场。' WHERE `entry` = 736;
UPDATE `mangos_string` SET `content_loc4` = '玩家人数不足。本场游戏将在 %u 分钟后关闭。' WHERE `entry` = 750;
UPDATE `mangos_string` SET `content_loc4` = '玩家人数不足。本场游戏将在 %u 秒后关闭。' WHERE `entry` = 751;
UPDATE `mangos_string` SET `content_loc4` = '只有联盟可以使用该传送门' WHERE `entry` = 752;
UPDATE `mangos_string` SET `content_loc4` = '只有部落可以使用该传送门' WHERE `entry` = 753;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 摧毁了！' WHERE `entry` = 759;
UPDATE `mangos_string` SET `content_loc4` = '%s 正遭受攻击！若不加以阻止，%s 将摧毁它！' WHERE `entry` = 760;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 761;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 762;
UPDATE `mangos_string` SET `content_loc4` = '%s 被 %s 占领了！' WHERE `entry` = 763;
UPDATE `mangos_string` SET `content_loc4` = '%s 正遭受攻击！若不加以阻止，%s 将占领它！' WHERE `entry` = 764;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s！其补给将被用于增援！' WHERE `entry` = 765;
UPDATE `mangos_string` SET `content_loc4` = '深铁矿洞' WHERE `entry` = 766;
UPDATE `mangos_string` SET `content_loc4` = '冷齿矿洞' WHERE `entry` = 767;
UPDATE `mangos_string` SET `content_loc4` = '雷矛急救站' WHERE `entry` = 768;
UPDATE `mangos_string` SET `content_loc4` = '丹巴达尔南部碉堡' WHERE `entry` = 769;
UPDATE `mangos_string` SET `content_loc4` = '丹巴达尔北部碉堡' WHERE `entry` = 770;
UPDATE `mangos_string` SET `content_loc4` = '雷矛墓地' WHERE `entry` = 771;
UPDATE `mangos_string` SET `content_loc4` = '冰翼碉堡' WHERE `entry` = 772;
UPDATE `mangos_string` SET `content_loc4` = '石炉墓地' WHERE `entry` = 773;
UPDATE `mangos_string` SET `content_loc4` = '石炉碉堡' WHERE `entry` = 774;
UPDATE `mangos_string` SET `content_loc4` = '雪落墓地' WHERE `entry` = 775;
UPDATE `mangos_string` SET `content_loc4` = '冰血哨塔' WHERE `entry` = 776;
UPDATE `mangos_string` SET `content_loc4` = '冰血墓地' WHERE `entry` = 777;
UPDATE `mangos_string` SET `content_loc4` = '哨塔高地' WHERE `entry` = 778;
UPDATE `mangos_string` SET `content_loc4` = '霜狼墓地' WHERE `entry` = 779;
UPDATE `mangos_string` SET `content_loc4` = '霜狼东部哨塔' WHERE `entry` = 780;
UPDATE `mangos_string` SET `content_loc4` = '霜狼西部哨塔' WHERE `entry` = 781;
UPDATE `mangos_string` SET `content_loc4` = '霜狼救济所' WHERE `entry` = 782;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗将在 1 分钟后开始。' WHERE `entry` = 784;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 785;
UPDATE `mangos_string` SET `content_loc4` = '奥特兰克山谷的战斗已经开始！' WHERE `entry` = 786;
UPDATE `mangos_string` SET `content_loc4` = '联盟的增援即将耗尽！' WHERE `entry` = 787;
UPDATE `mangos_string` SET `content_loc4` = '部落的增援即将耗尽！' WHERE `entry` = 788;
UPDATE `mangos_string` SET `content_loc4` = '霜狼将军已阵亡！' WHERE `entry` = 789;
UPDATE `mangos_string` SET `content_loc4` = '雷矛将军已阵亡！' WHERE `entry` = 790;
UPDATE `mangos_string` SET `content_loc4` = '进攻的时刻到了！为了部落！' WHERE `entry` = 792;
UPDATE `mangos_string` SET `content_loc4` = '振作起来，联盟！把这些恶徒赶出奥特兰克山谷！' WHERE `entry` = 793;
UPDATE `mangos_string` SET `content_loc4` = '你的金币不足' WHERE `entry` = 801;
UPDATE `mangos_string` SET `content_loc4` = '你没有足够的空余栏位' WHERE `entry` = 802;
UPDATE `mangos_string` SET `content_loc4` = '你的交易对象没有足够的空余背包栏位' WHERE `entry` = 803;
UPDATE `mangos_string` SET `content_loc4` = '你没有执行该操作的权限' WHERE `entry` = 804;
UPDATE `mangos_string` SET `content_loc4` = '未知语言' WHERE `entry` = 805;
UPDATE `mangos_string` SET `content_loc4` = '你不懂该语言' WHERE `entry` = 806;
UPDATE `mangos_string` SET `content_loc4` = '请提供角色名' WHERE `entry` = 807;
UPDATE `mangos_string` SET `content_loc4` = '未找到玩家 %s，或该玩家不在线' WHERE `entry` = 808;
UPDATE `mangos_string` SET `content_loc4` = '未找到角色 %s 所属的账号' WHERE `entry` = 809;
UPDATE `mangos_string` SET `content_loc4` = '公会会长' WHERE `entry` = 811;
UPDATE `mangos_string` SET `content_loc4` = '官员' WHERE `entry` = 812;
UPDATE `mangos_string` SET `content_loc4` = '老兵' WHERE `entry` = 813;
UPDATE `mangos_string` SET `content_loc4` = '成员' WHERE `entry` = 814;
UPDATE `mangos_string` SET `content_loc4` = '新成员' WHERE `entry` = 815;
UPDATE `mangos_string` SET `content_loc4` = '列兵' WHERE `entry` = 1400;
UPDATE `mangos_string` SET `content_loc4` = '下士' WHERE `entry` = 1401;
UPDATE `mangos_string` SET `content_loc4` = '中士' WHERE `entry` = 1402;
UPDATE `mangos_string` SET `content_loc4` = '军士长' WHERE `entry` = 1403;
UPDATE `mangos_string` SET `content_loc4` = '士官长' WHERE `entry` = 1404;
UPDATE `mangos_string` SET `content_loc4` = '骑士' WHERE `entry` = 1405;
UPDATE `mangos_string` SET `content_loc4` = '骑士中尉' WHERE `entry` = 1406;
UPDATE `mangos_string` SET `content_loc4` = '骑士队长' WHERE `entry` = 1407;
UPDATE `mangos_string` SET `content_loc4` = '骑士统领' WHERE `entry` = 1408;
UPDATE `mangos_string` SET `content_loc4` = '护卫骑士' WHERE `entry` = 1409;
UPDATE `mangos_string` SET `content_loc4` = '司令' WHERE `entry` = 1410;
UPDATE `mangos_string` SET `content_loc4` = '统帅' WHERE `entry` = 1411;
UPDATE `mangos_string` SET `content_loc4` = '司令统帅' WHERE `entry` = 1412;
UPDATE `mangos_string` SET `content_loc4` = '大统帅' WHERE `entry` = 1413;
UPDATE `mangos_string` SET `content_loc4` = '侦察兵' WHERE `entry` = 1414;
UPDATE `mangos_string` SET `content_loc4` = '步兵' WHERE `entry` = 1415;
UPDATE `mangos_string` SET `content_loc4` = '中士' WHERE `entry` = 1416;
UPDATE `mangos_string` SET `content_loc4` = '高阶军士' WHERE `entry` = 1417;
UPDATE `mangos_string` SET `content_loc4` = '一等军士长' WHERE `entry` = 1418;
UPDATE `mangos_string` SET `content_loc4` = '石头守卫' WHERE `entry` = 1419;
UPDATE `mangos_string` SET `content_loc4` = '血卫士' WHERE `entry` = 1420;
UPDATE `mangos_string` SET `content_loc4` = '军团士兵' WHERE `entry` = 1421;
UPDATE `mangos_string` SET `content_loc4` = '百夫长' WHERE `entry` = 1422;
UPDATE `mangos_string` SET `content_loc4` = '勇士' WHERE `entry` = 1423;
UPDATE `mangos_string` SET `content_loc4` = '中将' WHERE `entry` = 1424;
UPDATE `mangos_string` SET `content_loc4` = '将军' WHERE `entry` = 1425;
UPDATE `mangos_string` SET `content_loc4` = '督军' WHERE `entry` = 1426;
UPDATE `mangos_string` SET `content_loc4` = '高阶督军' WHERE `entry` = 1427;
UPDATE `mangos_string` SET `content_loc4` = '游戏管理员' WHERE `entry` = 1428;
UPDATE `mangos_string` SET `content_loc4` = '无军衔' WHERE `entry` = 1429;
UPDATE `mangos_string` SET `content_loc4` = '被唾弃 ' WHERE `entry` = 1430;
UPDATE `mangos_string` SET `content_loc4` = '被放逐 ' WHERE `entry` = 1431;
UPDATE `mangos_string` SET `content_loc4` = '亡命者 ' WHERE `entry` = 1432;
UPDATE `mangos_string` SET `content_loc4` = '贱民 ' WHERE `entry` = 1433;
UPDATE `mangos_string` SET `content_loc4` = '玩家：%s - %s（军衔 %u）' WHERE `entry` = 1434;
UPDATE `mangos_string` SET `content_loc4` = '今日：[荣誉击杀：|c0000ff00%u|r] [非荣誉击杀：|c00ff0000%u|r]' WHERE `entry` = 1435;
UPDATE `mangos_string` SET `content_loc4` = '昨日：[击杀：|c0000ff00%u|r] [荣誉：%u]' WHERE `entry` = 1436;
UPDATE `mangos_string` SET `content_loc4` = '本周：[击杀：|c0000ff00%u|r] [荣誉：%u]' WHERE `entry` = 1437;
UPDATE `mangos_string` SET `content_loc4` = '上周：[击杀：|c0000ff00%u|r] [荣誉：%u] [排名：%u]' WHERE `entry` = 1438;
UPDATE `mangos_string` SET `content_loc4` = '生涯：[军衔分数：|c0000ff00%f|r] [荣誉击杀：|c0000ff00%u|r] [非荣誉击杀：|c00ff0000%u|r] [最高军衔 %u：%s]' WHERE `entry` = 1439;
UPDATE `mangos_string` SET `content_loc4` = '我想看看你的货物。' WHERE `entry` = 2000;
UPDATE `mangos_string` SET `content_loc4` = '训练我！' WHERE `entry` = 2001;
UPDATE `mangos_string` SET `content_loc4` = '%s 试图因恐惧而逃跑！' WHERE `entry` = 5030;
UPDATE `mangos_string` SET `content_loc4` = '%s 已复活（在线）' WHERE `entry` = 5031;
UPDATE `mangos_string` SET `content_loc4` = '%s 已复活（离线）' WHERE `entry` = 5032;
UPDATE `mangos_string` SET `content_loc4` = '|cffffff00[|c1f40af20GM 公告，发布者|r |cffff0000%s|cffffff00]:|r |c1111ff00 %s|r' WHERE `entry` = 6615;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了北地哨塔！' WHERE `entry` = 10033;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了北地哨塔！' WHERE `entry` = 10034;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了东墙哨塔！' WHERE `entry` = 10035;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了东墙哨塔！' WHERE `entry` = 10036;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了皇冠哨塔！' WHERE `entry` = 10037;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了皇冠哨塔！' WHERE `entry` = 10038;
UPDATE `mangos_string` SET `content_loc4` = '部落占领了病木林哨塔！' WHERE `entry` = 10039;
UPDATE `mangos_string` SET `content_loc4` = '联盟占领了病木林哨塔！' WHERE `entry` = 10040;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了北地哨塔！' WHERE `entry` = 10041;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了北地哨塔！' WHERE `entry` = 10042;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了东墙哨塔！' WHERE `entry` = 10043;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了东墙哨塔！' WHERE `entry` = 10044;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了皇冠哨塔！' WHERE `entry` = 10045;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了皇冠哨塔！' WHERE `entry` = 10046;
UPDATE `mangos_string` SET `content_loc4` = '部落失去了病木林哨塔！' WHERE `entry` = 10047;
UPDATE `mangos_string` SET `content_loc4` = '联盟失去了病木林哨塔！' WHERE `entry` = 10048;
UPDATE `mangos_string` SET `content_loc4` = '部落已收集 200 份异种蝎壳！' WHERE `entry` = 10049;
UPDATE `mangos_string` SET `content_loc4` = '联盟已收集 200 份异种蝎壳！' WHERE `entry` = 10050;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗将在 1 分钟后开始。' WHERE `entry` = 10051;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗将在 30 秒后开始。做好准备！' WHERE `entry` = 10052;
UPDATE `mangos_string` SET `content_loc4` = '阳光林地山谷的战斗，开始吧！' WHERE `entry` = 10053;
UPDATE `mangos_string` SET `content_loc4` = '%s 占领了 %s' WHERE `entry` = 10054;
UPDATE `mangos_string` SET `content_loc4` = '$n 防守住了 %s' WHERE `entry` = 10055;
UPDATE `mangos_string` SET `content_loc4` = '$n 袭击了 %s' WHERE `entry` = 10056;
UPDATE `mangos_string` SET `content_loc4` = '$n 宣称占领了 %s！若无人争夺，%s 将在 1 分钟后控制它！' WHERE `entry` = 10057;
UPDATE `mangos_string` SET `content_loc4` = '往日的宿怨导致了你的失败，真是可惜……' WHERE `entry` = 10058;
UPDATE `mangos_string` SET `content_loc4` = '时间流已被改变，我们无法确定是哪些事件导致了偏移，如今它将产生难以预料的影响。' WHERE `entry` = 10059;
UPDATE `mangos_string` SET `content_loc4` = '决战在即，英雄们。加入战斗，在你的敌人中找出潜伏的永恒龙军团密探！' WHERE `entry` = 10060;
UPDATE `mangos_string` SET `content_loc4` = '林荫郡塔' WHERE `entry` = 10061;
UPDATE `mangos_string` SET `content_loc4` = '戈尔德雷加塔' WHERE `entry` = 10062;
UPDATE `mangos_string` SET `content_loc4` = '英勇堡' WHERE `entry` = 10063;
UPDATE `mangos_string` SET `content_loc4` = '加入英文社区频道（/join WorldEN）与其他玩家交流！' WHERE `entry` = 11011;
UPDATE `mangos_string` SET `content_loc4` = '使用命令 “.go warsong”、“.go arathi” 和 “.go alterac” 可以从任何地方加入战场！' WHERE `entry` = 11012;
UPDATE `mangos_string` SET `content_loc4` = '为帮助服务器人口增长，请发起拉新活动！提供 60 级 NPC，支持从其他服务器导入角色，欢迎关注我们的 Facebook！' WHERE `entry` = 11013;
UPDATE `mangos_string` SET `content_loc4` = '服务器将于 8 月 19 日停机以进行国际版发布，详情请见论坛' WHERE `entry` = 11014;
UPDATE `mangos_string` SET `content_loc4` = 'Nostalrius 是一个 PVP 与 PVE 服务器。但请注意，试图恶心其他玩家的行为将受到惩罚。' WHERE `entry` = 11015;
UPDATE `mangos_string` SET `content_loc4` = '赏金猎人系统已开放。联系游戏管理员，为某人开出你的悬赏价，详情请见论坛的活动版块。' WHERE `entry` = 11016;
UPDATE `mangos_string` SET `content_loc4` = '这是 Turtle-WoW 1.18.1 的非官方延续版本' WHERE `entry` = 50009;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：在官方服上就是这么运作的……|r' WHERE `entry` = 50200;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：术士太强了！|r' WHERE `entry` = 50201;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：火抗被高估了。|r' WHERE `entry` = 50202;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：你以为你想，其实你不想。|r' WHERE `entry` = 50203;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：那边的草更绿……|r' WHERE `entry` = 50204;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：防护骑也能当坦克！|r' WHERE `entry` = 50205;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：谁也不会只拉一只鱼人！|r' WHERE `entry` = 50206;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：神圣抗性什么的……|r' WHERE `entry` = 50207;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：在 Nostalrius 上一切都是正常的。|r' WHERE `entry` = 50208;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：你知道侏儒做的鞋最好吗？难的是把脚塞进他们那张小嘴里。|r' WHERE `entry` = 50209;
UPDATE `mangos_string` SET `content_loc4` = '|cffF58CBA千真之剑：咚咚咚。谁啊？是个侏儒，我够不着门铃！|r' WHERE `entry` = 50210;
UPDATE `mangos_string` SET `content_loc4` = '悲剧发生了。硬核角色 %s（等级 %u）%s。愿这份牺牲不被遗忘。' WHERE `entry` = 50300;
UPDATE `mangos_string` SET `content_loc4` = '%s 在硬核模式下达到了 %u 级！随着其向不朽攀登，荣耀日益增长！然而，所面临的危险也与日俱增。' WHERE `entry` = 50301;
UPDATE `mangos_string` SET `content_loc4` = '%s 超越了死亡，在硬核模式下一次未死地达到了 60 级！从今往后，%s 将被称为不朽者！' WHERE `entry` = 50302;
UPDATE `mangos_string` SET `content_loc4` = '%s 完成了 2800 个任务，如今被称为求知者，激励着同道冒险者去探索未知！' WHERE `entry` = 50305;
UPDATE `mangos_string` SET `content_loc4` = '你需要先选中一个角色或生物。' WHERE `entry` = 1;
UPDATE `mangos_string` SET `content_loc4` = '你需要先选中一个生物。' WHERE `entry` = 2;
UPDATE `mangos_string` SET `content_loc4` = '|cffffff00%s|r' WHERE `entry` = 3;
UPDATE `mangos_string` SET `content_loc4` = '该命令没有帮助信息' WHERE `entry` = 5;
UPDATE `mangos_string` SET `content_loc4` = '没有这个命令' WHERE `entry` = 6;
UPDATE `mangos_string` SET `content_loc4` = '没有这个子命令' WHERE `entry` = 7;
UPDATE `mangos_string` SET `content_loc4` = '命令 %s 含有子命令：' WHERE `entry` = 8;
UPDATE `mangos_string` SET `content_loc4` = '你可用的命令：' WHERE `entry` = 9;
UPDATE `mangos_string` SET `content_loc4` = '语法错误。' WHERE `entry` = 10;
UPDATE `mangos_string` SET `content_loc4` = '你的账号等级为：%u' WHERE `entry` = 11;
UPDATE `mangos_string` SET `content_loc4` = '在线玩家：%u（上限：%u） 排队玩家：%u（上限：%u）' WHERE `entry` = 12;
UPDATE `mangos_string` SET `content_loc4` = '服务器已运行：%s' WHERE `entry` = 13;
UPDATE `mangos_string` SET `content_loc4` = '玩家已保存。' WHERE `entry` = 14;
UPDATE `mangos_string` SET `content_loc4` = '所有玩家已保存。' WHERE `entry` = 15;
UPDATE `mangos_string` SET `content_loc4` = '当前服务器上有以下在线管理员：' WHERE `entry` = 16;
UPDATE `mangos_string` SET `content_loc4` = '当前服务器上没有在线管理员。' WHERE `entry` = 17;
UPDATE `mangos_string` SET `content_loc4` = '，等级 ' WHERE `entry` = 30;
UPDATE `mangos_string` SET `content_loc4` = ' [已学会]' WHERE `entry` = 31;
UPDATE `mangos_string` SET `content_loc4` = ' [可学习]' WHERE `entry` = 32;
UPDATE `mangos_string` SET `content_loc4` = ' [被动]' WHERE `entry` = 33;
UPDATE `mangos_string` SET `content_loc4` = ' [天赋]' WHERE `entry` = 34;
UPDATE `mangos_string` SET `content_loc4` = ' [主动]' WHERE `entry` = 35;
UPDATE `mangos_string` SET `content_loc4` = ' [已完成]' WHERE `entry` = 36;
UPDATE `mangos_string` SET `content_loc4` = '（离线）' WHERE `entry` = 37;
UPDATE `mangos_string` SET `content_loc4` = '关' WHERE `entry` = 39;
UPDATE `mangos_string` SET `content_loc4` = '你是：%s' WHERE `entry` = 40;
UPDATE `mangos_string` SET `content_loc4` = '可见' WHERE `entry` = 41;
UPDATE `mangos_string` SET `content_loc4` = '不可见' WHERE `entry` = 42;
UPDATE `mangos_string` SET `content_loc4` = '完成' WHERE `entry` = 43;
UPDATE `mangos_string` SET `content_loc4` = '你' WHERE `entry` = 44;
UPDATE `mangos_string` SET `content_loc4` = ' <未知> ' WHERE `entry` = 45;
UPDATE `mangos_string` SET `content_loc4` = '<错误>' WHERE `entry` = 46;
UPDATE `mangos_string` SET `content_loc4` = '<不存在的角色>' WHERE `entry` = 47;
UPDATE `mangos_string` SET `content_loc4` = '未知' WHERE `entry` = 48;
UPDATE `mangos_string` SET `content_loc4` = '物品 %u 的数量（%u）无效' WHERE `entry` = 52;
UPDATE `mangos_string` SET `content_loc4` = '邮件最多只能有 %u 组物品' WHERE `entry` = 53;
UPDATE `mangos_string` SET `content_loc4` = '当前每日消息：\n%s' WHERE `entry` = 56;
UPDATE `mangos_string` SET `content_loc4` = '使用世界数据库：%s' WHERE `entry` = 57;
UPDATE `mangos_string` SET `content_loc4` = '使用脚本库：%s' WHERE `entry` = 58;
UPDATE `mangos_string` SET `content_loc4` = '使用生物事件 AI：%s' WHERE `entry` = 59;
UPDATE `mangos_string` SET `content_loc4` = '用户名：' WHERE `entry` = 61;
UPDATE `mangos_string` SET `content_loc4` = '密码：' WHERE `entry` = 62;
UPDATE `mangos_string` SET `content_loc4` = '接受密语' WHERE `entry` = 63;
UPDATE `mangos_string` SET `content_loc4` = '不接受密语' WHERE `entry` = 64;
UPDATE `mangos_string` SET `content_loc4` = '使用脚本库：<未知脚本库>' WHERE `entry` = 65;
UPDATE `mangos_string` SET `content_loc4` = '使用脚本库：<未加载脚本库>' WHERE `entry` = 66;
UPDATE `mangos_string` SET `content_loc4` = '全服通知：' WHERE `entry` = 100;
UPDATE `mangos_string` SET `content_loc4` = '地图：%u（%s） 区域：%u（%s） 地区：%u（%s）\nX：%f Y：%f Z：%f 朝向：%f\ngrid[%u,%u]cell[%u,%u] 副本 ID：%u\n 区域 X：%f 区域 Y：%f\n地面 Z：%f 地板 Z：%f 有高度数据（地图：%u 可见地图：%u）' WHERE `entry` = 101;
UPDATE `mangos_string` SET `content_loc4` = '%s 正在被传送。' WHERE `entry` = 102;
UPDATE `mangos_string` SET `content_loc4` = '只有当目标玩家和你在同一小队且你是队长时，才能把他召唤到你的副本。' WHERE `entry` = 103;
UPDATE `mangos_string` SET `content_loc4` = '你现在处于小队中，无法前往该玩家的副本。' WHERE `entry` = 104;
UPDATE `mangos_string` SET `content_loc4` = '只有开启管理员模式时，你才能在不在对方小队的情况下前往他的副本。' WHERE `entry` = 105;
UPDATE `mangos_string` SET `content_loc4` = '无法将玩家 %s 在副本之间传送。' WHERE `entry` = 106;
UPDATE `mangos_string` SET `content_loc4` = '无法将玩家 %s 在副本之间召唤。' WHERE `entry` = 107;
UPDATE `mangos_string` SET `content_loc4` = '你正在召唤 %s%s。' WHERE `entry` = 108;
UPDATE `mangos_string` SET `content_loc4` = '你正被 %s 召唤。' WHERE `entry` = 109;
UPDATE `mangos_string` SET `content_loc4` = '你正在将 %s%s 传送到 %s。' WHERE `entry` = 110;
UPDATE `mangos_string` SET `content_loc4` = '你正被 %s 传送。' WHERE `entry` = 111;
UPDATE `mangos_string` SET `content_loc4` = '玩家（%s）不存在。' WHERE `entry` = 112;
UPDATE `mangos_string` SET `content_loc4` = '出现在 %s 的位置（在线）。' WHERE `entry` = 113;
UPDATE `mangos_string` SET `content_loc4` = '%s 出现在你的位置。' WHERE `entry` = 114;
UPDATE `mangos_string` SET `content_loc4` = '数值无效。' WHERE `entry` = 115;
UPDATE `mangos_string` SET `content_loc4` = '未选择角色。' WHERE `entry` = 116;
UPDATE `mangos_string` SET `content_loc4` = '%s 不在队伍中。' WHERE `entry` = 117;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的生命值改为 %i/%i。' WHERE `entry` = 118;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的生命值改为 %i/%i。' WHERE `entry` = 119;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的法力值改为 %i/%i。' WHERE `entry` = 120;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的法力值改为 %i/%i。' WHERE `entry` = 121;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的能量值改为 %i/%i。' WHERE `entry` = 122;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的能量值改为 %i/%i。' WHERE `entry` = 123;
UPDATE `mangos_string` SET `content_loc4` = '当前能量：%u' WHERE `entry` = 124;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的怒气值改为 %i/%i。' WHERE `entry` = 125;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的怒气值改为 %i/%i。' WHERE `entry` = 126;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的等级改为 %i。' WHERE `entry` = 127;
UPDATE `mangos_string` SET `content_loc4` = 'GUID %i，阵营 %i，标记 %i，NPC 标记 %i，动态标记 %i' WHERE `entry` = 128;
UPDATE `mangos_string` SET `content_loc4` = '阵营错误：%u（未在 factiontemplate.dbc 中找到）。' WHERE `entry` = 129;
UPDATE `mangos_string` SET `content_loc4` = '你将 GUID=%i 的阵营改为 %i，标记改为 %i，NPC 标记改为 %i，动态标记改为 %i。' WHERE `entry` = 130;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的法术系位 %u 的法术调整值 %u 改为 %i。' WHERE `entry` = 131;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的法术系位 %u 的法术调整值 %u 改为 %i。' WHERE `entry` = 132;
UPDATE `mangos_string` SET `content_loc4` = '%s 现在可以使用所有飞行点（直到登出）。' WHERE `entry` = 133;
UPDATE `mangos_string` SET `content_loc4` = '%s 不再能使用所有飞行点（只能使用已探索的）。' WHERE `entry` = 134;
UPDATE `mangos_string` SET `content_loc4` = '%s 为你开放了所有飞行点（直到登出）。' WHERE `entry` = 135;
UPDATE `mangos_string` SET `content_loc4` = '%s 移除了所有飞行点权限（仍可使用已探索的）。' WHERE `entry` = 136;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的所有移动速度设为正常值的 %2.2f 倍。' WHERE `entry` = 137;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的所有移动速度设为正常值的 %2.2f 倍。' WHERE `entry` = 138;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的移动速度设为正常值的 %2.2f 倍。' WHERE `entry` = 139;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的移动速度设为正常值的 %2.2f 倍。' WHERE `entry` = 140;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的游泳速度设为正常值的 %2.2f 倍。' WHERE `entry` = 141;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的游泳速度设为正常值的 %2.2f 倍。' WHERE `entry` = 142;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的倒退速度设为正常值的 %2.2f 倍。' WHERE `entry` = 143;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的倒退速度设为正常值的 %2.2f 倍。' WHERE `entry` = 144;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的飞行点飞行速度设为正常值的 %2.2f 倍。' WHERE `entry` = 145;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的飞行点飞行速度设为正常值的 %2.2f 倍。' WHERE `entry` = 146;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的体型设为 %2.2f。' WHERE `entry` = 147;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的体型设为 %2.2f。' WHERE `entry` = 148;
UPDATE `mangos_string` SET `content_loc4` = '没有这种坐骑。' WHERE `entry` = 149;
UPDATE `mangos_string` SET `content_loc4` = '你给了 %s 一个坐骑。' WHERE `entry` = 150;
UPDATE `mangos_string` SET `content_loc4` = '%s 给了你一个坐骑。' WHERE `entry` = 151;
UPDATE `mangos_string` SET `content_loc4` = 'USER1: %i, ADD: %i, DIF: %i\n' WHERE `entry` = 152;
UPDATE `mangos_string` SET `content_loc4` = '你取走了 %s 所有的铜币。' WHERE `entry` = 153;
UPDATE `mangos_string` SET `content_loc4` = '%s 取走了你所有的铜币。' WHERE `entry` = 154;
UPDATE `mangos_string` SET `content_loc4` = '你从 %s 处取走了 %i 铜币。' WHERE `entry` = 155;
UPDATE `mangos_string` SET `content_loc4` = '%s 从你处取走了 %i 铜币。' WHERE `entry` = 156;
UPDATE `mangos_string` SET `content_loc4` = '你给了 %s %i 铜币。' WHERE `entry` = 157;
UPDATE `mangos_string` SET `content_loc4` = '%s 给了你 %i 铜币。' WHERE `entry` = 158;
UPDATE `mangos_string` SET `content_loc4` = '你听到音效 %u。' WHERE `entry` = 159;
UPDATE `mangos_string` SET `content_loc4` = 'USER2: %i, ADD: %i, RESULT: %i\n' WHERE `entry` = 160;
UPDATE `mangos_string` SET `content_loc4` = '已移除字段 %i 中的位 %i。' WHERE `entry` = 161;
UPDATE `mangos_string` SET `content_loc4` = '已设置字段 %i 中的位 %i。' WHERE `entry` = 162;
UPDATE `mangos_string` SET `content_loc4` = '传送点表为空！' WHERE `entry` = 163;
UPDATE `mangos_string` SET `content_loc4` = '未找到传送点！' WHERE `entry` = 164;
UPDATE `mangos_string` SET `content_loc4` = '需要搜索参数。' WHERE `entry` = 165;
UPDATE `mangos_string` SET `content_loc4` = '没有匹配你请求的传送点。' WHERE `entry` = 166;
UPDATE `mangos_string` SET `content_loc4` = '找到以下地点：\n %s' WHERE `entry` = 168;
UPDATE `mangos_string` SET `content_loc4` = '邮件已发送给 %s' WHERE `entry` = 169;
UPDATE `mangos_string` SET `content_loc4` = '你尝试试听音效 %u，但它不存在。' WHERE `entry` = 170;
UPDATE `mangos_string` SET `content_loc4` = '你不能把自己传送给自己！' WHERE `entry` = 171;
UPDATE `mangos_string` SET `content_loc4` = '服务器控制台命令' WHERE `entry` = 172;
UPDATE `mangos_string` SET `content_loc4` = '液面高度：%f，地面：%f，类型：%d，状态：%d' WHERE `entry` = 175;
UPDATE `mangos_string` SET `content_loc4` = '出现在 %s 的位置（离线）。' WHERE `entry` = 176;
UPDATE `mangos_string` SET `content_loc4` = '未选中任何目标。' WHERE `entry` = 200;
UPDATE `mangos_string` SET `content_loc4` = '物件 GUID 为：%s' WHERE `entry` = 201;
UPDATE `mangos_string` SET `content_loc4` = '名称超出 %i 个字符。' WHERE `entry` = 202;
UPDATE `mangos_string` SET `content_loc4` = '错误，名称只能包含字母 A-Z 和 a-z。' WHERE `entry` = 203;
UPDATE `mangos_string` SET `content_loc4` = '副标题超出 %i 个字符。' WHERE `entry` = 204;
UPDATE `mangos_string` SET `content_loc4` = '尚未实现' WHERE `entry` = 205;
UPDATE `mangos_string` SET `content_loc4` = '物品 \'%i\' \'%s\' 已加入列表，最大数量 \'%i\'，补充时间 \'%i\' ' WHERE `entry` = 206;
UPDATE `mangos_string` SET `content_loc4` = '数据库中未找到物品 \'%i\'。' WHERE `entry` = 207;
UPDATE `mangos_string` SET `content_loc4` = '物品 \'%i\' \'%s\' 已从商人列表中删除' WHERE `entry` = 208;
UPDATE `mangos_string` SET `content_loc4` = '商人列表中未找到物品 \'%i\'。' WHERE `entry` = 209;
UPDATE `mangos_string` SET `content_loc4` = '物品 \'%i\' 已在商人列表中。' WHERE `entry` = 210;
UPDATE `mangos_string` SET `content_loc4` = '%s 的法术已重置。' WHERE `entry` = 211;
UPDATE `mangos_string` SET `content_loc4` = '%s 的法术将在下次登录时重置。' WHERE `entry` = 212;
UPDATE `mangos_string` SET `content_loc4` = '%s 的天赋已重置。' WHERE `entry` = 213;
UPDATE `mangos_string` SET `content_loc4` = '%s 的天赋将在下次登录时重置。' WHERE `entry` = 214;
UPDATE `mangos_string` SET `content_loc4` = '你的法术已重置。' WHERE `entry` = 215;
UPDATE `mangos_string` SET `content_loc4` = '你的天赋已重置。' WHERE `entry` = 216;
UPDATE `mangos_string` SET `content_loc4` = '.resetall 命令的 \'%s\' 分支未知。请输入完整正确的分支名。' WHERE `entry` = 217;
UPDATE `mangos_string` SET `content_loc4` = '所有玩家的法术将在登录时重置。强烈建议重新登录！' WHERE `entry` = 218;
UPDATE `mangos_string` SET `content_loc4` = '所有玩家的天赋将在登录时重置。强烈建议重新登录！' WHERE `entry` = 219;
UPDATE `mangos_string` SET `content_loc4` = '找不到 %s 的路径点 id %u（位于路径 %i，来自 %s）' WHERE `entry` = 220;
UPDATE `mangos_string` SET `content_loc4` = '找不到 %s 的最后一个路径点' WHERE `entry` = 221;
UPDATE `mangos_string` SET `content_loc4` = '%s 没有路径或路径为空，路径 id %i（来自 %s）' WHERE `entry` = 222;
UPDATE `mangos_string` SET `content_loc4` = '生物（GUID：%u）未找到路径点 —— 这是 MaNGOS 数据库问题（单个浮点数）。' WHERE `entry` = 223;
UPDATE `mangos_string` SET `content_loc4` = '无法在地图上访问 %s，也许你离它的刷新位置太远了' WHERE `entry` = 224;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物（GUID：%u）' WHERE `entry` = 225;
UPDATE `mangos_string` SET `content_loc4` = '你必须选中一个可视化路径点。' WHERE `entry` = 226;
UPDATE `mangos_string` SET `content_loc4` = '未找到可视化路径点' WHERE `entry` = 227;
UPDATE `mangos_string` SET `content_loc4` = '无法创建生物 ID 为 %d 的可视化路径点' WHERE `entry` = 228;
UPDATE `mangos_string` SET `content_loc4` = '所有可视化路径点已移除' WHERE `entry` = 229;
UPDATE `mangos_string` SET `content_loc4` = '无法将路径点 %u 添加到 %s（路径 ID %i，由 %s 存储）' WHERE `entry` = 230;
UPDATE `mangos_string` SET `content_loc4` = '未提供 GUID。' WHERE `entry` = 231;
UPDATE `mangos_string` SET `content_loc4` = '未提供路径点编号。' WHERE `entry` = 232;
UPDATE `mangos_string` SET `content_loc4` = '\'%s\' 需要参数。' WHERE `entry` = 233;
UPDATE `mangos_string` SET `content_loc4` = '已将路径点 %u 添加到 %s（路径 ID %i，路径由 %s 存储）' WHERE `entry` = 234;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 235;
UPDATE `mangos_string` SET `content_loc4` = '路径点已修改。' WHERE `entry` = 236;
UPDATE `mangos_string` SET `content_loc4` = '路径点 %s 已修改。' WHERE `entry` = 237;
UPDATE `mangos_string` SET `content_loc4` = '路径点导出成功。' WHERE `entry` = 238;
UPDATE `mangos_string` SET `content_loc4` = '数据库中未找到路径点。' WHERE `entry` = 239;
UPDATE `mangos_string` SET `content_loc4` = '文件已导入。' WHERE `entry` = 240;
UPDATE `mangos_string` SET `content_loc4` = '路径点已移除。' WHERE `entry` = 241;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 242;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 243;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 244;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 245;
UPDATE `mangos_string` SET `content_loc4` = '%s 的路径点 %u（来自路径 ID %i，由 %s 存储）' WHERE `entry` = 246;
UPDATE `mangos_string` SET `content_loc4` = ' 等待时间：%d' WHERE `entry` = 247;
UPDATE `mangos_string` SET `content_loc4` = ' 朝向：%f' WHERE `entry` = 248;
UPDATE `mangos_string` SET `content_loc4` = ' 脚本 ID：%u' WHERE `entry` = 249;
UPDATE `mangos_string` SET `content_loc4` = '脚本 ID 被设为不存在的 %u，请将其加入 DBScriptsEngine 并重载该表。' WHERE `entry` = 250;
UPDATE `mangos_string` SET `content_loc4` = '未使用' WHERE `entry` = 251;
UPDATE `mangos_string` SET `content_loc4` = 'AI 脚本名：%s' WHERE `entry` = 252;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s 的强制改名将在下次登录时申请。' WHERE `entry` = 253;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s（GUID #%u）的强制改名将在下次登录时申请。' WHERE `entry` = 254;
UPDATE `mangos_string` SET `content_loc4` = '未找到路径点生物（GUID：%u）' WHERE `entry` = 255;
UPDATE `mangos_string` SET `content_loc4` = '找不到该 NPC……' WHERE `entry` = 256;
UPDATE `mangos_string` SET `content_loc4` = '生物移动类型已设为 \'%s\'，路径点已移除（若有）。' WHERE `entry` = 257;
UPDATE `mangos_string` SET `content_loc4` = '生物移动类型已设为 \'%s\'，路径点未移除。' WHERE `entry` = 258;
UPDATE `mangos_string` SET `content_loc4` = '数值错误，请使用 on 或 off' WHERE `entry` = 259;
UPDATE `mangos_string` SET `content_loc4` = '数值已保存。' WHERE `entry` = 260;
UPDATE `mangos_string` SET `content_loc4` = '数值已保存，你可能需要重新登录或清理客户端缓存。' WHERE `entry` = 261;
UPDATE `mangos_string` SET `content_loc4` = '未找到区域触发器 ID %u！' WHERE `entry` = 262;
UPDATE `mangos_string` SET `content_loc4` = '目标地图或坐标无效（X：%f Y：%f 地图 ID：%u）' WHERE `entry` = 263;
UPDATE `mangos_string` SET `content_loc4` = '区域坐标无效（X：%f Y：%f 地区 ID：%u）' WHERE `entry` = 264;
UPDATE `mangos_string` SET `content_loc4` = '区域 %u（%s）属于可设副本的地图 %u（%s）' WHERE `entry` = 265;
UPDATE `mangos_string` SET `content_loc4` = '什么也没找到！' WHERE `entry` = 266;
UPDATE `mangos_string` SET `content_loc4` = '未找到物件！' WHERE `entry` = 267;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物！' WHERE `entry` = 268;
UPDATE `mangos_string` SET `content_loc4` = '生物已移除' WHERE `entry` = 270;
UPDATE `mangos_string` SET `content_loc4` = '生物已移动。' WHERE `entry` = 271;
UPDATE `mangos_string` SET `content_loc4` = '生物（GUID：%u）必须与玩家处于同一地图！' WHERE `entry` = 272;
UPDATE `mangos_string` SET `content_loc4` = '未找到物件（GUID：%u）' WHERE `entry` = 273;
UPDATE `mangos_string` SET `content_loc4` = '物件（GUID：%u）在未找到的所属 %s 物件列表中有引用，无法删除。' WHERE `entry` = 274;
UPDATE `mangos_string` SET `content_loc4` = '物件（GUID：%u）已移除' WHERE `entry` = 275;
UPDATE `mangos_string` SET `content_loc4` = '物件 |cffffffff|Hgameobject:%d|h[%s]|h|r（GUID：%u）已旋转' WHERE `entry` = 276;
UPDATE `mangos_string` SET `content_loc4` = '物件 |cffffffff|Hgameobject:%d|h[%s]|h|r（GUID：%u）已移动' WHERE `entry` = 277;
UPDATE `mangos_string` SET `content_loc4` = '你必须选中一名商人' WHERE `entry` = 278;
UPDATE `mangos_string` SET `content_loc4` = '你必须提供物品 ID' WHERE `entry` = 279;
UPDATE `mangos_string` SET `content_loc4` = '商人的物品过多（上限 128）' WHERE `entry` = 280;
UPDATE `mangos_string` SET `content_loc4` = '不能踢出自己，请直接登出' WHERE `entry` = 281;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s 已被踢出。' WHERE `entry` = 282;
UPDATE `mangos_string` SET `content_loc4` = '接受密语：%s' WHERE `entry` = 284;
UPDATE `mangos_string` SET `content_loc4` = '接受密语：开' WHERE `entry` = 285;
UPDATE `mangos_string` SET `content_loc4` = '接受密语：关' WHERE `entry` = 286;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物（GUID：%u）' WHERE `entry` = 287;
UPDATE `mangos_string` SET `content_loc4` = '工单数：%i 显示新工单：%s\n' WHERE `entry` = 288;
UPDATE `mangos_string` SET `content_loc4` = '来自 %s 的新工单' WHERE `entry` = 289;
UPDATE `mangos_string` SET `content_loc4` = '%s 的工单（最后更新：%s）：\n%s ' WHERE `entry` = 290;
UPDATE `mangos_string` SET `content_loc4` = '新工单提示：开' WHERE `entry` = 291;
UPDATE `mangos_string` SET `content_loc4` = '新工单提示：关' WHERE `entry` = 292;
UPDATE `mangos_string` SET `content_loc4` = '工单 %i 不存在' WHERE `entry` = 293;
UPDATE `mangos_string` SET `content_loc4` = '所有工单已删除。' WHERE `entry` = 294;
UPDATE `mangos_string` SET `content_loc4` = '角色 %s 的工单已删除。' WHERE `entry` = 295;
UPDATE `mangos_string` SET `content_loc4` = '工单已删除。' WHERE `entry` = 296;
UPDATE `mangos_string` SET `content_loc4` = '刷新距离已改为：%f' WHERE `entry` = 297;
UPDATE `mangos_string` SET `content_loc4` = '刷新时间已改为：%i' WHERE `entry` = 298;
UPDATE `mangos_string` SET `content_loc4` = '%s 的 %s 字段已被设为 %u' WHERE `entry` = 299;
UPDATE `mangos_string` SET `content_loc4` = '%s 的阵营 %s（%u）声望已被设为 %5d！' WHERE `entry` = 305;
UPDATE `mangos_string` SET `content_loc4` = '未找到阵营！' WHERE `entry` = 307;
UPDATE `mangos_string` SET `content_loc4` = '阵营 %i 未知！' WHERE `entry` = 308;
UPDATE `mangos_string` SET `content_loc4` = '参数 %s 无效' WHERE `entry` = 309;
UPDATE `mangos_string` SET `content_loc4` = 'delta 必须介于 0 与 %d 之间（含两端）' WHERE `entry` = 310;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE `entry` = 311;
UPDATE `mangos_string` SET `content_loc4` = ' [可见]' WHERE `entry` = 312;
UPDATE `mangos_string` SET `content_loc4` = ' [交战]' WHERE `entry` = 313;
UPDATE `mangos_string` SET `content_loc4` = ' [强制和平]' WHERE `entry` = 314;
UPDATE `mangos_string` SET `content_loc4` = ' [隐藏]' WHERE `entry` = 315;
UPDATE `mangos_string` SET `content_loc4` = ' [强制不可见]' WHERE `entry` = 316;
UPDATE `mangos_string` SET `content_loc4` = ' [未激活]' WHERE `entry` = 317;
UPDATE `mangos_string` SET `content_loc4` = '阵营 %s（%u）不能拥有声望。' WHERE `entry` = 326;
UPDATE `mangos_string` SET `content_loc4` = ' [无声望]' WHERE `entry` = 327;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 下的角色（ID：%u）' WHERE `entry` = 328;
UPDATE `mangos_string` SET `content_loc4` = '  %s（GUID %u）' WHERE `entry` = 329;
UPDATE `mangos_string` SET `content_loc4` = '未找到玩家！' WHERE `entry` = 330;
UPDATE `mangos_string` SET `content_loc4` = '扩展物品费用 %u 不存在' WHERE `entry` = 331;
UPDATE `mangos_string` SET `content_loc4` = '管理员模式：开' WHERE `entry` = 332;
UPDATE `mangos_string` SET `content_loc4` = '管理员模式：关' WHERE `entry` = 333;
UPDATE `mangos_string` SET `content_loc4` = '管理员聊天标识：开' WHERE `entry` = 334;
UPDATE `mangos_string` SET `content_loc4` = '管理员聊天标识：关' WHERE `entry` = 335;
UPDATE `mangos_string` SET `content_loc4` = '你修复了 %s 的所有物品。' WHERE `entry` = 336;
UPDATE `mangos_string` SET `content_loc4` = '你的所有物品已被 %s 修复。' WHERE `entry` = 337;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的水上行走模式设为 %s。' WHERE `entry` = 338;
UPDATE `mangos_string` SET `content_loc4` = '你的水上行走模式被 %s 设为 %s。' WHERE `entry` = 339;
UPDATE `mangos_string` SET `content_loc4` = '%s 现在开始跟随你。' WHERE `entry` = 340;
UPDATE `mangos_string` SET `content_loc4` = '%s 没有跟随你。' WHERE `entry` = 341;
UPDATE `mangos_string` SET `content_loc4` = '%s 现在不再跟随你。' WHERE `entry` = 342;
UPDATE `mangos_string` SET `content_loc4` = '未找到飞行点 ID %u！' WHERE `entry` = 347;
UPDATE `mangos_string` SET `content_loc4` = '物件（编号：%u）数据无效，无法刷新' WHERE `entry` = 348;
UPDATE `mangos_string` SET `content_loc4` = '区域触发器 %u 没有目标坐标' WHERE `entry` = 357;
UPDATE `mangos_string` SET `content_loc4` = '未找到区域触发器！' WHERE `entry` = 358;
UPDATE `mangos_string` SET `content_loc4` = '%s|cffffffff|Hareatrigger_target:%u|h[触发器目标 %u]|h|r 地图 %u X：%f Y：%f Z：%f%s' WHERE `entry` = 359;
UPDATE `mangos_string` SET `content_loc4` = '%s[触发器目标 %u] 地图 %u X：%f Y：%f Z：%f' WHERE `entry` = 360;
UPDATE `mangos_string` SET `content_loc4` = '|cffffffff|Hareatrigger:%u|h[触发器 %u]|h|r 地图 %u X：%f Y：%f Z：%f%s%s%s' WHERE `entry` = 361;
UPDATE `mangos_string` SET `content_loc4` = '[触发器 %u] 地图 %u X：%f Y：%f Z：%f%s%s' WHERE `entry` = 362;
UPDATE `mangos_string` SET `content_loc4` = '（距离 %f）' WHERE `entry` = 363;
UPDATE `mangos_string` SET `content_loc4` = ' [旅店]' WHERE `entry` = 364;
UPDATE `mangos_string` SET `content_loc4` = ' [任务]' WHERE `entry` = 365;
UPDATE `mangos_string` SET `content_loc4` = '探索任务：' WHERE `entry` = 366;
UPDATE `mangos_string` SET `content_loc4` = '需要等级 %u' WHERE `entry` = 367;
UPDATE `mangos_string` SET `content_loc4` = '回复：\n%s ' WHERE `entry` = 373;
UPDATE `mangos_string` SET `content_loc4` = '工单数：%i\n' WHERE `entry` = 374;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s 没有工单。' WHERE `entry` = 375;
UPDATE `mangos_string` SET `content_loc4` = '%u - |cffffffff|Hpool:%u|h[%s]|h|r 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u' WHERE `entry` = 376;
UPDATE `mangos_string` SET `content_loc4` = '地图 \'%s\'（ID：%u）未找到卡池。' WHERE `entry` = 377;
UPDATE `mangos_string` SET `content_loc4` = '你无法在不可设副本的地图 \'%s\'（ID：%u）上使用此命令。请改用 .lookup pool 命令。' WHERE `entry` = 378;
UPDATE `mangos_string` SET `content_loc4` = '你无法在不可设副本的地图 \'%s\'（ID：%u）上不带参数使用此命令。' WHERE `entry` = 379;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hcreature:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r 几率：%f %s' WHERE `entry` = 380;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - [%s] X：%f Y：%f Z：%f 地图 ID：%d 几率：%f %s' WHERE `entry` = 381;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hcreature:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r %s' WHERE `entry` = 382;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - [%s] X：%f Y：%f Z：%f 地图 ID：%d %s' WHERE `entry` = 383;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hgameobject:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r 几率：%f %s' WHERE `entry` = 384;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - [%s] X：%f Y：%f Z：%f 地图 ID：%d 几率：%f %s' WHERE `entry` = 385;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hgameobject:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r %s' WHERE `entry` = 386;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - [%s] X：%f Y：%f Z：%f 地图 ID：%d %s' WHERE `entry` = 387;
UPDATE `mangos_string` SET `content_loc4` = '设定明确几率的生物：' WHERE `entry` = 388;
UPDATE `mangos_string` SET `content_loc4` = '几率均等的生物：' WHERE `entry` = 389;
UPDATE `mangos_string` SET `content_loc4` = '设定明确几率的物件：' WHERE `entry` = 390;
UPDATE `mangos_string` SET `content_loc4` = '几率均等的物件：' WHERE `entry` = 391;
UPDATE `mangos_string` SET `content_loc4` = '卡池 %u - 母卡池：%u |cffffffff|Hpool:%u|h[%s]|h|r 自动刷新：%u 上限：%u' WHERE `entry` = 392;
UPDATE `mangos_string` SET `content_loc4` = '卡池 %u - 母卡池：%u [%s] 自动刷新：%u 上限：%u' WHERE `entry` = 393;
UPDATE `mangos_string` SET `content_loc4` = '卡池 %u - 无母卡池 自动刷新：%u 上限：%u' WHERE `entry` = 394;
UPDATE `mangos_string` SET `content_loc4` = '未找到卡池' WHERE `entry` = 395;
UPDATE `mangos_string` SET `content_loc4` = '%u - [%s] 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u' WHERE `entry` = 396;
UPDATE `mangos_string` SET `content_loc4` = '设定明确几率的卡池：' WHERE `entry` = 397;
UPDATE `mangos_string` SET `content_loc4` = '几率均等的卡池：' WHERE `entry` = 398;
UPDATE `mangos_string` SET `content_loc4` = '%u - |cffffffff|Hpool:%u|h[%s]|h|r 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u 几率：%f %s' WHERE `entry` = 399;
UPDATE `mangos_string` SET `content_loc4` = '|cffff0000[系统消息]:|r脚本已重载' WHERE `entry` = 400;
UPDATE `mangos_string` SET `content_loc4` = '你将账号 %s 的安全等级改为 %i。' WHERE `entry` = 401;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的安全等级改为 %i。' WHERE `entry` = 402;
UPDATE `mangos_string` SET `content_loc4` = '你的安全等级不足以执行此操作。' WHERE `entry` = 403;
UPDATE `mangos_string` SET `content_loc4` = '生物移动已禁用。' WHERE `entry` = 404;
UPDATE `mangos_string` SET `content_loc4` = '生物移动已启用。' WHERE `entry` = 405;
UPDATE `mangos_string` SET `content_loc4` = '无法更改此区域的天气。' WHERE `entry` = 406;
UPDATE `mangos_string` SET `content_loc4` = '服务器已禁用天气系统。' WHERE `entry` = 407;
UPDATE `mangos_string` SET `content_loc4` = '未找到 %s %s' WHERE `entry` = 410;
UPDATE `mangos_string` SET `content_loc4` = '%s 已解封。备注：%s' WHERE `entry` = 411;
UPDATE `mangos_string` SET `content_loc4` = '解除 %s 的封禁时出错。' WHERE `entry` = 412;
UPDATE `mangos_string` SET `content_loc4` = '账号不存在：%s' WHERE `entry` = 413;
UPDATE `mangos_string` SET `content_loc4` = '没有这个角色。' WHERE `entry` = 414;
UPDATE `mangos_string` SET `content_loc4` = '封禁列表中没有这个 IP。' WHERE `entry` = 415;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 从未被封禁过' WHERE `entry` = 416;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 的封禁记录：' WHERE `entry` = 417;
UPDATE `mangos_string` SET `content_loc4` = '封禁日期：%s 封禁时长：%s 仍然有效：%s 原因：%s 操作者：%s' WHERE `entry` = 418;
UPDATE `mangos_string` SET `content_loc4` = '无限' WHERE `entry` = 419;
UPDATE `mangos_string` SET `content_loc4` = '从不' WHERE `entry` = 420;
UPDATE `mangos_string` SET `content_loc4` = '是' WHERE `entry` = 421;
UPDATE `mangos_string` SET `content_loc4` = 'IP：%s\n封禁日期：%s\n解封日期：%s\n剩余：%s\n原因：%s\n操作者：%s' WHERE `entry` = 423;
UPDATE `mangos_string` SET `content_loc4` = '没有匹配的 IP 封禁。' WHERE `entry` = 424;
UPDATE `mangos_string` SET `content_loc4` = '没有匹配的账号。' WHERE `entry` = 425;
UPDATE `mangos_string` SET `content_loc4` = '没有匹配该片段的被封禁账号拥有角色。' WHERE `entry` = 426;
UPDATE `mangos_string` SET `content_loc4` = '以下 IP 符合你的模式：' WHERE `entry` = 427;
UPDATE `mangos_string` SET `content_loc4` = '以下账号符合你的查询：' WHERE `entry` = 428;
UPDATE `mangos_string` SET `content_loc4` = '找到物品 %u：%u（背包 %u 邮件 %u 拍卖行 %u 公会 %u）' WHERE `entry` = 438;
UPDATE `mangos_string` SET `content_loc4` = '找到物件 %u：%u ' WHERE `entry` = 439;
UPDATE `mangos_string` SET `content_loc4` = '找到生物 %u：%u ' WHERE `entry` = 441;
UPDATE `mangos_string` SET `content_loc4` = '墓地 #%u 不存在。' WHERE `entry` = 449;
UPDATE `mangos_string` SET `content_loc4` = '墓地 #%u 已链接到区域 #%u（当前）。' WHERE `entry` = 450;
UPDATE `mangos_string` SET `content_loc4` = '墓地 #%u 已链接到区域 #%u（当前）。' WHERE `entry` = 451;
UPDATE `mangos_string` SET `content_loc4` = '墓地 #%u 无法链接到子区域或不存在的区域 #%u（内部错误）。' WHERE `entry` = 452;
UPDATE `mangos_string` SET `content_loc4` = '墓地 id= #%u 中没有阵营，请修正你的数据库' WHERE `entry` = 454;
UPDATE `mangos_string` SET `content_loc4` = '阵营无效，请修正数据库' WHERE `entry` = 455;
UPDATE `mangos_string` SET `content_loc4` = '任意' WHERE `entry` = 456;
UPDATE `mangos_string` SET `content_loc4` = '联盟' WHERE `entry` = 457;
UPDATE `mangos_string` SET `content_loc4` = '部落' WHERE `entry` = 458;
UPDATE `mangos_string` SET `content_loc4` = '墓地 #%u（阵营：%s）是链接到区域 #%u 的最近墓地。' WHERE `entry` = 459;
UPDATE `mangos_string` SET `content_loc4` = '区域 #%u 没有链接的墓地。' WHERE `entry` = 460;
UPDATE `mangos_string` SET `content_loc4` = '区域 #%u 没有该阵营的链接墓地：%s。' WHERE `entry` = 461;
UPDATE `mangos_string` SET `content_loc4` = '传送点已存在！' WHERE `entry` = 462;
UPDATE `mangos_string` SET `content_loc4` = '传送点已添加。' WHERE `entry` = 463;
UPDATE `mangos_string` SET `content_loc4` = '传送点未添加：数据库错误。' WHERE `entry` = 464;
UPDATE `mangos_string` SET `content_loc4` = '传送点已删除。' WHERE `entry` = 465;
UPDATE `mangos_string` SET `content_loc4` = '未找到飞行点！' WHERE `entry` = 466;
UPDATE `mangos_string` SET `content_loc4` = '目标单位有 %d 个光环：' WHERE `entry` = 467;
UPDATE `mangos_string` SET `content_loc4` = 'id：%d 效果：%d 类型：%d 持续时间：%d 最大持续时间：%d 周期计时：%d 层数：%d 名称：%s%s%s 施法者：%s' WHERE `entry` = 468;
UPDATE `mangos_string` SET `content_loc4` = '目标单位有 %d 个类型 %d 的光环：' WHERE `entry` = 469;
UPDATE `mangos_string` SET `content_loc4` = 'id：%d 效果：%d 名称：%s%s%s 施法者：%s' WHERE `entry` = 470;
UPDATE `mangos_string` SET `content_loc4` = '任务 %u 从物品开始。为使其正常工作，请把物品加入背包并以正常方式开始任务：.additem %u' WHERE `entry` = 472;
UPDATE `mangos_string` SET `content_loc4` = ' [已奖励]' WHERE `entry` = 474;
UPDATE `mangos_string` SET `content_loc4` = ' [已完成]' WHERE `entry` = 475;
UPDATE `mangos_string` SET `content_loc4` = ' [进行中]' WHERE `entry` = 476;
UPDATE `mangos_string` SET `content_loc4` = '%s 的飞行模式 %s' WHERE `entry` = 477;
UPDATE `mangos_string` SET `content_loc4` = '已向 %s 发送操作码 %u' WHERE `entry` = 478;
UPDATE `mangos_string` SET `content_loc4` = '角色载入成功！' WHERE `entry` = 479;
UPDATE `mangos_string` SET `content_loc4` = '角色载入失败！' WHERE `entry` = 480;
UPDATE `mangos_string` SET `content_loc4` = '角色转储成功！' WHERE `entry` = 481;
UPDATE `mangos_string` SET `content_loc4` = '角色转储失败！' WHERE `entry` = 482;
UPDATE `mangos_string` SET `content_loc4` = '法术 %u 已损坏，无法施放或学习！' WHERE `entry` = 483;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s 的技能 %u（%s）已设为 %u，当前上限设为 %u（不含永久（天赋）加成）。' WHERE `entry` = 484;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s 必须先拥有技能 %u（%s）才能使用此命令。' WHERE `entry` = 485;
UPDATE `mangos_string` SET `content_loc4` = '技能 ID（%u）无效' WHERE `entry` = 486;
UPDATE `mangos_string` SET `content_loc4` = '你已学习默认的管理员法术/技能。' WHERE `entry` = 487;
UPDATE `mangos_string` SET `content_loc4` = '你已经学会该法术了。' WHERE `entry` = 488;
UPDATE `mangos_string` SET `content_loc4` = '目标（%s）已经学会该法术了。' WHERE `entry` = 489;
UPDATE `mangos_string` SET `content_loc4` = '%s 没有学会该法术。' WHERE `entry` = 490;
UPDATE `mangos_string` SET `content_loc4` = '你已经遗忘该法术了。' WHERE `entry` = 491;
UPDATE `mangos_string` SET `content_loc4` = '已移除 %s 的所有法术冷却。' WHERE `entry` = 492;
UPDATE `mangos_string` SET `content_loc4` = '已移除 %s 的法术 %u 冷却。' WHERE `entry` = 493;
UPDATE `mangos_string` SET `content_loc4` = '命令：Additem，物品 ID = %i，数量 = %i' WHERE `entry` = 494;
UPDATE `mangos_string` SET `content_loc4` = '命令：Additemset，套装 ID = %i' WHERE `entry` = 495;
UPDATE `mangos_string` SET `content_loc4` = '已从 %s 移除物品 ID = %i，数量 = %i' WHERE `entry` = 496;
UPDATE `mangos_string` SET `content_loc4` = '无法创建物品 \'%i\'（数量：%i）' WHERE `entry` = 497;
UPDATE `mangos_string` SET `content_loc4` = '你需要提供一个公会名称！' WHERE `entry` = 498;
UPDATE `mangos_string` SET `content_loc4` = '未找到玩家！' WHERE `entry` = 499;
UPDATE `mangos_string` SET `content_loc4` = '玩家已经有公会了！' WHERE `entry` = 500;
UPDATE `mangos_string` SET `content_loc4` = '公会未创建！（是否已存在？）' WHERE `entry` = 501;
UPDATE `mangos_string` SET `content_loc4` = '未找到套装 \'%u\' 中的物品。' WHERE `entry` = 502;
UPDATE `mangos_string` SET `content_loc4` = '距离为：（3D）%f（2D）%f - （3D，点对点）%f 码。' WHERE `entry` = 503;
UPDATE `mangos_string` SET `content_loc4` = '物品 \'%i\' \'%s\' 物品栏位 %i' WHERE `entry` = 504;
UPDATE `mangos_string` SET `content_loc4` = '虚拟物品栏位（%u）无效' WHERE `entry` = 505;
UPDATE `mangos_string` SET `content_loc4` = '物品 \'%i\' \'%s\' 已加入栏位 %i' WHERE `entry` = 506;
UPDATE `mangos_string` SET `content_loc4` = '物品保存失败！' WHERE `entry` = 507;
UPDATE `mangos_string` SET `content_loc4` = '%d - 所有者：%s（guid：%u 账号：%u）%s' WHERE `entry` = 508;
UPDATE `mangos_string` SET `content_loc4` = '%d - 寄件人：%s（guid：%u 账号：%u）收件人：%s（guid：%u 账号：%u）%s' WHERE `entry` = 509;
UPDATE `mangos_string` SET `content_loc4` = '%d - 所有者：%s（guid：%u 账号：%u）%s' WHERE `entry` = 510;
UPDATE `mangos_string` SET `content_loc4` = '链接类型错误！' WHERE `entry` = 511;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s' WHERE `entry` = 512;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE `entry` = 513;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE `entry` = 514;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hcreature:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r ' WHERE `entry` = 515;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE `entry` = 516;
UPDATE `mangos_string` SET `content_loc4` = '%d%s，编号 %d - |cffffffff|Hgameobject:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r' WHERE `entry` = 517;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE `entry` = 518;
UPDATE `mangos_string` SET `content_loc4` = '|cffffffff|Htele:%s|h[%s]|h|r ' WHERE `entry` = 519;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE `entry` = 520;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE `entry` = 521;
UPDATE `mangos_string` SET `content_loc4` = '未找到物件（编号：%u）' WHERE `entry` = 522;
UPDATE `mangos_string` SET `content_loc4` = '>> 物件 %s（GUID：%u）位于 %f %f %f。朝向 %f。' WHERE `entry` = 523;
UPDATE `mangos_string` SET `content_loc4` = '已选物件：\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID：%u ID：%u\nX：%f Y：%f Z：%f 地图 ID：%u\n朝向：%f' WHERE `entry` = 524;
UPDATE `mangos_string` SET `content_loc4` = '>> 已添加物件 \'%i\'（%s）（GUID：%i）位于 \'%f %f %f\'。' WHERE `entry` = 525;
UPDATE `mangos_string` SET `content_loc4` = '%s（lowguid：%u）的移动生成器栈：' WHERE `entry` = 526;
UPDATE `mangos_string` SET `content_loc4` = '   空闲' WHERE `entry` = 527;
UPDATE `mangos_string` SET `content_loc4` = '   随机' WHERE `entry` = 528;
UPDATE `mangos_string` SET `content_loc4` = '   路径点' WHERE `entry` = 529;
UPDATE `mangos_string` SET `content_loc4` = '   动物随机' WHERE `entry` = 530;
UPDATE `mangos_string` SET `content_loc4` = '   困惑' WHERE `entry` = 531;
UPDATE `mangos_string` SET `content_loc4` = '   以玩家 %s 为目标（lowguid %u）' WHERE `entry` = 532;
UPDATE `mangos_string` SET `content_loc4` = '   以生物 %s 为目标（lowguid %u）' WHERE `entry` = 533;
UPDATE `mangos_string` SET `content_loc4` = '   以 <空> 为目标' WHERE `entry` = 534;
UPDATE `mangos_string` SET `content_loc4` = '   返回原位移动至（X：%f Y：%f Z：%f）' WHERE `entry` = 535;
UPDATE `mangos_string` SET `content_loc4` = '   返回原位移动被用于玩家？！？' WHERE `entry` = 536;
UPDATE `mangos_string` SET `content_loc4` = '   飞行点飞行' WHERE `entry` = 537;
UPDATE `mangos_string` SET `content_loc4` = '   未知移动生成器（%u）' WHERE `entry` = 538;
UPDATE `mangos_string` SET `content_loc4` = '已选玩家：%s。\n阵营：%u。\nNPC 标记：%u。\n编号：%u。\n外观 ID：%u（原始：%u）。' WHERE `entry` = 539;
UPDATE `mangos_string` SET `content_loc4` = '等级：%u。' WHERE `entry` = 540;
UPDATE `mangos_string` SET `content_loc4` = '生命值（基础）：%u。（最大）：%u。（当前）：%u。' WHERE `entry` = 541;
UPDATE `mangos_string` SET `content_loc4` = '单位标记：%u。\n动态标记：%u。\n阵营模板：%u。' WHERE `entry` = 542;
UPDATE `mangos_string` SET `content_loc4` = '掉落：%u 偷窃：%u 剥皮：%u' WHERE `entry` = 543;
UPDATE `mangos_string` SET `content_loc4` = '位置：%f %f %f。' WHERE `entry` = 544;
UPDATE `mangos_string` SET `content_loc4` = '*** 是商人！' WHERE `entry` = 545;
UPDATE `mangos_string` SET `content_loc4` = '*** 是训练师！' WHERE `entry` = 546;
UPDATE `mangos_string` SET `content_loc4` = '副本 ID：%u' WHERE `entry` = 547;
UPDATE `mangos_string` SET `content_loc4` = '玩家%s %s（guid：%u）账号：%s（id：%u%s）管理员等级：%u 上次 IP：%s%s 上次登录：%s 延迟：%ums 客户端：%s' WHERE `entry` = 548;
UPDATE `mangos_string` SET `content_loc4` = '游戏时间：%s 等级：%u 金钱：%ug%us%uc 邮箱收件：%ug%us%uc 邮箱发件：%ug%us%uc' WHERE `entry` = 549;
UPDATE `mangos_string` SET `content_loc4` = '.pinfo 命令不支持离线玩家的 \'rep\' 选项。' WHERE `entry` = 550;
UPDATE `mangos_string` SET `content_loc4` = '%s 现在已探索所有区域。' WHERE `entry` = 551;
UPDATE `mangos_string` SET `content_loc4` = '%s 不再探索任何区域。' WHERE `entry` = 552;
UPDATE `mangos_string` SET `content_loc4` = '%s 为你开放了所有区域的地图。' WHERE `entry` = 553;
UPDATE `mangos_string` SET `content_loc4` = '%s 为你隐藏了所有区域的地图。' WHERE `entry` = 554;
UPDATE `mangos_string` SET `content_loc4` = '悬浮已启用' WHERE `entry` = 555;
UPDATE `mangos_string` SET `content_loc4` = '悬浮已禁用' WHERE `entry` = 556;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的等级提升到（%i）' WHERE `entry` = 557;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的等级降低到（%i）' WHERE `entry` = 558;
UPDATE `mangos_string` SET `content_loc4` = '%s 重置了你的等级进度。' WHERE `entry` = 559;
UPDATE `mangos_string` SET `content_loc4` = '该地区已被标记为已探索。' WHERE `entry` = 560;
UPDATE `mangos_string` SET `content_loc4` = '该地区已被标记为未探索。' WHERE `entry` = 561;
UPDATE `mangos_string` SET `content_loc4` = '找不到公会。' WHERE `entry` = 562;
UPDATE `mangos_string` SET `content_loc4` = '邀请玩家加入公会时出错。' WHERE `entry` = 563;
UPDATE `mangos_string` SET `content_loc4` = '数值索引 %u 对 %s 来说太大（数量：%u）。' WHERE `entry` = 564;
UPDATE `mangos_string` SET `content_loc4` = '已将 %s 的字段 %u 设为 uint32 值：%u' WHERE `entry` = 565;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的字段 %u 设为 uint32 值：%u' WHERE `entry` = 566;
UPDATE `mangos_string` SET `content_loc4` = '已将 %s 的字段 %u 设为 float 值：%f' WHERE `entry` = 567;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的字段 %u 设为 float 值：%f' WHERE `entry` = 568;
UPDATE `mangos_string` SET `content_loc4` = '获取 %s 的 uint32 值：[字段]：%u [值]：%u' WHERE `entry` = 569;
UPDATE `mangos_string` SET `content_loc4` = '%s 的 uint32 值：[字段]：%u [值]：%u' WHERE `entry` = 570;
UPDATE `mangos_string` SET `content_loc4` = '获取 %s 的 float 值：[字段]：%u [值]：%f' WHERE `entry` = 571;
UPDATE `mangos_string` SET `content_loc4` = '%s 的 float 值：[字段]：%u [值]：%f' WHERE `entry` = 572;
UPDATE `mangos_string` SET `content_loc4` = '将 %s 的 uint32 字段 %u 加上：%i = %u（%i）' WHERE `entry` = 575;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的 uint32 字段 %u 加上：%i = %u（%i）' WHERE `entry` = 576;
UPDATE `mangos_string` SET `content_loc4` = '你现在处于隐身状态（等级 %u）' WHERE `entry` = 577;
UPDATE `mangos_string` SET `content_loc4` = '你现在处于可见状态。' WHERE `entry` = 578;
UPDATE `mangos_string` SET `content_loc4` = '选中的玩家或生物没有攻击目标。' WHERE `entry` = 579;
UPDATE `mangos_string` SET `content_loc4` = '你已学会种族/职业的所有默认法术，并完成了奖励法术的任务。' WHERE `entry` = 580;
UPDATE `mangos_string` SET `content_loc4` = '附近找到的物件（距离 %f）：%u ' WHERE `entry` = 581;
UPDATE `mangos_string` SET `content_loc4` = '刷新时间：完整：%s 剩余：%s' WHERE `entry` = 582;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE `entry` = 583;
UPDATE `mangos_string` SET `content_loc4` = '未找到事件！' WHERE `entry` = 584;
UPDATE `mangos_string` SET `content_loc4` = '事件不存在！' WHERE `entry` = 585;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u：%s%s\n开始：%s 结束：%s 出现次数：%s 持续时间：%s\n下次状态变更：%s' WHERE `entry` = 586;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 已激活！' WHERE `entry` = 587;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 未激活！' WHERE `entry` = 588;
UPDATE `mangos_string` SET `content_loc4` = '   点移动至（X：%f Y：%f Z：%f）' WHERE `entry` = 589;
UPDATE `mangos_string` SET `content_loc4` = '   恐惧移动' WHERE `entry` = 590;
UPDATE `mangos_string` SET `content_loc4` = '   迷惑移动' WHERE `entry` = 591;
UPDATE `mangos_string` SET `content_loc4` = '你已学会 %s 专业的所有法术' WHERE `entry` = 592;
UPDATE `mangos_string` SET `content_loc4` = '当前被封禁的账号：' WHERE `entry` = 593;
UPDATE `mangos_string` SET `content_loc4` = '|    账号      |    封禁日期   |   解封日期   |    操作者     |    封禁原因   |' WHERE `entry` = 594;
UPDATE `mangos_string` SET `content_loc4` = '当前被封禁的 IP：' WHERE `entry` = 595;
UPDATE `mangos_string` SET `content_loc4` = '|      IP       |   封禁日期   |   解封日期   |    操作者     |    封禁原因   |' WHERE `entry` = 596;
UPDATE `mangos_string` SET `content_loc4` = '当前管理员：' WHERE `entry` = 597;
UPDATE `mangos_string` SET `content_loc4` = '|    账号      |  管理员等级  |' WHERE `entry` = 598;
UPDATE `mangos_string` SET `content_loc4` = '没有管理员。' WHERE `entry` = 599;
UPDATE `mangos_string` SET `content_loc4` = '%s %s%s %s（guid：%u）账号：%s（id：%u%s）管理员等级：%u 上次 IP：%s%s 上次登录：%s 延迟：%ums 客户端：%s 两步验证：%s' WHERE `entry` = 616;
UPDATE `mangos_string` SET `content_loc4` = '未找到音效。' WHERE `entry` = 617;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Hsound:%d|h[%s]|h|r ' WHERE `entry` = 618;
UPDATE `mangos_string` SET `content_loc4` = '队伍类型：%s（ID：%s）队长：%s 玩家数：%d 玩家：%s' WHERE `entry` = 640;
UPDATE `mangos_string` SET `content_loc4` = '战场已设为 1v0 以便调试。' WHERE `entry` = 739;
UPDATE `mangos_string` SET `content_loc4` = '战场已恢复正常玩家人数。' WHERE `entry` = 740;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的力量改为 %i。' WHERE `entry` = 900;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的力量改为 %i。' WHERE `entry` = 901;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的敏捷改为 %i。' WHERE `entry` = 902;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的敏捷改为 %i。' WHERE `entry` = 903;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的耐力改为 %i。' WHERE `entry` = 904;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的耐力改为 %i。' WHERE `entry` = 905;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的智力改为 %i。' WHERE `entry` = 906;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的智力改为 %i。' WHERE `entry` = 907;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的精神改为 %i。' WHERE `entry` = 908;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的精神改为 %i。' WHERE `entry` = 909;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的护甲改为 %i。' WHERE `entry` = 910;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的护甲改为 %i。' WHERE `entry` = 911;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的神圣抗性改为 %i。' WHERE `entry` = 912;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的神圣抗性改为 %i。' WHERE `entry` = 913;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的火焰抗性改为 %i。' WHERE `entry` = 914;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的火焰抗性改为 %i。' WHERE `entry` = 915;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的自然抗性改为 %i。' WHERE `entry` = 916;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的自然抗性改为 %i。' WHERE `entry` = 917;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的冰霜抗性改为 %i。' WHERE `entry` = 918;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的冰霜抗性改为 %i。' WHERE `entry` = 919;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的暗影抗性改为 %i。' WHERE `entry` = 920;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的暗影抗性改为 %i。' WHERE `entry` = 921;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的奥术抗性改为 %i。' WHERE `entry` = 922;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的奥术抗性改为 %i。' WHERE `entry` = 923;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的近战攻击强度改为 %i。' WHERE `entry` = 924;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的近战攻击强度改为 %i。' WHERE `entry` = 925;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的远程攻击强度改为 %i。' WHERE `entry` = 926;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的远程攻击强度改为 %i。' WHERE `entry` = 927;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的法术强度改为 %i。' WHERE `entry` = 928;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的法术强度改为 %i。' WHERE `entry` = 929;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的近战爆击几率改为 %g%%。' WHERE `entry` = 930;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的近战爆击几率改为 %g%%。' WHERE `entry` = 931;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的远程爆击几率改为 %g%%。' WHERE `entry` = 932;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的远程爆击几率改为 %g%%。' WHERE `entry` = 933;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的法术爆击几率改为 %g%%。' WHERE `entry` = 934;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的法术爆击几率改为 %g%%。' WHERE `entry` = 935;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的主手速度改为 %i 毫秒。' WHERE `entry` = 936;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的主手速度改为 %i 毫秒。' WHERE `entry` = 937;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的副手速度改为 %i 毫秒。' WHERE `entry` = 938;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的副手速度改为 %i 毫秒。' WHERE `entry` = 939;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的远程速度改为 %i 毫秒。' WHERE `entry` = 940;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的远程速度改为 %i 毫秒。' WHERE `entry` = 941;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的施法速度改为 %g 倍。' WHERE `entry` = 942;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的施法速度改为 %g 倍。' WHERE `entry` = 943;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的格挡几率改为 %g%%。' WHERE `entry` = 944;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的格挡几率改为 %g%%。' WHERE `entry` = 945;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的躲闪几率改为 %g%%。' WHERE `entry` = 946;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的躲闪几率改为 %g%%。' WHERE `entry` = 947;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的招架几率改为 %g%%。' WHERE `entry` = 948;
UPDATE `mangos_string` SET `content_loc4` = '%s 将你的招架几率改为 %g%%。' WHERE `entry` = 949;
UPDATE `mangos_string` SET `content_loc4` = '正在退出守护进程……' WHERE `entry` = 1000;
UPDATE `mangos_string` SET `content_loc4` = '账号已删除：%s' WHERE `entry` = 1001;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 未删除（可能是 sql 文件格式已更新）' WHERE `entry` = 1002;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 未删除（未知错误）' WHERE `entry` = 1003;
UPDATE `mangos_string` SET `content_loc4` = '账号已创建：%s' WHERE `entry` = 1004;
UPDATE `mangos_string` SET `content_loc4` = '账号名不能超过 16 个字符（客户端限制），账号未创建！' WHERE `entry` = 1005;
UPDATE `mangos_string` SET `content_loc4` = '已存在同名账号！' WHERE `entry` = 1006;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 未创建（可能是 sql 文件格式已更新）' WHERE `entry` = 1007;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s 未创建（未知错误）' WHERE `entry` = 1008;
UPDATE `mangos_string` SET `content_loc4` = '玩家 %s（Guid：%u）账号 %s（Id：%u）已删除。' WHERE `entry` = 1009;
UPDATE `mangos_string` SET `content_loc4` = '| ID         |    账号       |       角色           |       IP        | 管理员 | 资料片 |' WHERE `entry` = 1010;
UPDATE `mangos_string` SET `content_loc4` = '没有在线玩家。' WHERE `entry` = 1014;
UPDATE `mangos_string` SET `content_loc4` = '使用的 quit 命令输入不完整，需要完整输入（quit），或该命令不是在远程管理控制台中使用的。' WHERE `entry` = 1015;
UPDATE `mangos_string` SET `content_loc4` = '| GUID       | 名称                 | 账号                         | 删除日期            |' WHERE `entry` = 1016;
UPDATE `mangos_string` SET `content_loc4` = '未找到角色。' WHERE `entry` = 1019;
UPDATE `mangos_string` SET `content_loc4` = '正在恢复以下角色：' WHERE `entry` = 1020;
UPDATE `mangos_string` SET `content_loc4` = '正在删除以下角色：' WHERE `entry` = 1021;
UPDATE `mangos_string` SET `content_loc4` = '错误：只有当你只选中一个角色时才能分配新名称！' WHERE `entry` = 1022;
UPDATE `mangos_string` SET `content_loc4` = '角色 \'%s\'（GUID：%u 账号 %u）无法恢复：账号不存在！' WHERE `entry` = 1023;
UPDATE `mangos_string` SET `content_loc4` = '角色 \'%s\'（GUID：%u 账号 %u）无法恢复：账号角色列表已满！' WHERE `entry` = 1024;
UPDATE `mangos_string` SET `content_loc4` = '角色 \'%s\'（GUID：%u 账号 %u）将被改名，因为该名称已被占用！' WHERE `entry` = 1025;
UPDATE `mangos_string` SET `content_loc4` = 'GUID：%u 名称：%s 账号：%s（%u）日期：%s' WHERE `entry` = 1026;
UPDATE `mangos_string` SET `content_loc4` = '日志过滤状态：' WHERE `entry` = 1027;
UPDATE `mangos_string` SET `content_loc4` = '所有日志过滤已设为：%s' WHERE `entry` = 1028;
UPDATE `mangos_string` SET `content_loc4` = '该命令只能在远程管理控制台中调用。' WHERE `entry` = 1029;
UPDATE `mangos_string` SET `content_loc4` = '活动物件：%d。可见性修正：%0.2f' WHERE `entry` = 1030;
UPDATE `mangos_string` SET `content_loc4` = '装备 ID：%u。' WHERE `entry` = 1031;
UPDATE `mangos_string` SET `content_loc4` = '栖息类型：%u' WHERE `entry` = 1032;
UPDATE `mangos_string` SET `content_loc4` = '护甲：%u' WHERE `entry` = 1033;
UPDATE `mangos_string` SET `content_loc4` = 'AI 名称：%s 脚本名：%s' WHERE `entry` = 1034;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s（Id：%u）现在最多可使用到资料片 %u。' WHERE `entry` = 1100;
UPDATE `mangos_string` SET `content_loc4` = '每日消息已更改为：\n%s' WHERE `entry` = 1101;
UPDATE `mangos_string` SET `content_loc4` = '已向 %s 发送消息：%s' WHERE `entry` = 1102;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - %s X：%f Y：%f Z：%f 地图 ID：%d' WHERE `entry` = 1110;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - %s X：%f Y：%f Z：%f 地图 ID：%d' WHERE `entry` = 1111;
UPDATE `mangos_string` SET `content_loc4` = '无法打开文件：%s' WHERE `entry` = 1112;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s（%u）已达到允许的角色数量上限（客户端限制）' WHERE `entry` = 1113;
UPDATE `mangos_string` SET `content_loc4` = '转储文件数据已损坏！' WHERE `entry` = 1114;
UPDATE `mangos_string` SET `content_loc4` = '角色名称无效！' WHERE `entry` = 1115;
UPDATE `mangos_string` SET `content_loc4` = '角色 guid 无效！' WHERE `entry` = 1116;
UPDATE `mangos_string` SET `content_loc4` = '角色 guid %u 已被占用！' WHERE `entry` = 1117;
UPDATE `mangos_string` SET `content_loc4` = '%d - 公会：%s（guid：%u）%s' WHERE `entry` = 1118;
UPDATE `mangos_string` SET `content_loc4` = '性别必须使用 male 或 female。' WHERE `entry` = 1119;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的性别改为 %s。' WHERE `entry` = 1120;
UPDATE `mangos_string` SET `content_loc4` = '你的性别被 %s 改为 %s。' WHERE `entry` = 1121;
UPDATE `mangos_string` SET `content_loc4` = '（%u/%u +永久 %u +临时 %u）' WHERE `entry` = 1122;
UPDATE `mangos_string` SET `content_loc4` = '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r（地图：%u X：%f Y：%f Z：%f）' WHERE `entry` = 1128;
UPDATE `mangos_string` SET `content_loc4` = '%d - %s %s（地图：%u X：%f Y：%f Z：%f）' WHERE `entry` = 1129;
UPDATE `mangos_string` SET `content_loc4` = '事件已开始 %u “%s”' WHERE `entry` = 1130;
UPDATE `mangos_string` SET `content_loc4` = '事件已停止 %u “%s”' WHERE `entry` = 1131;
UPDATE `mangos_string` SET `content_loc4` = '   跟随玩家 %s（lowguid %u）' WHERE `entry` = 1132;
UPDATE `mangos_string` SET `content_loc4` = '   跟随生物 %s（lowguid %u）' WHERE `entry` = 1133;
UPDATE `mangos_string` SET `content_loc4` = '   跟随 <空>' WHERE `entry` = 1134;
UPDATE `mangos_string` SET `content_loc4` = '已学天赋列表：' WHERE `entry` = 1135;
UPDATE `mangos_string` SET `content_loc4` = '   （找到天赋：%u 已用天赋点：%u）' WHERE `entry` = 1136;
UPDATE `mangos_string` SET `content_loc4` = '%d%s - |cffffffff|Hgameobject:%d|h[%s X：%f Y：%f Z：%f 地图 ID：%d]|h|r ' WHERE `entry` = 1137;
UPDATE `mangos_string` SET `content_loc4` = '| GUID       | 名称                 | 种族            | 职业            | 等级  |' WHERE `entry` = 1139;
UPDATE `mangos_string` SET `content_loc4` = '%u - |cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u' WHERE `entry` = 1141;
UPDATE `mangos_string` SET `content_loc4` = '%u - %s（在线：%s IP：%s 管理员：%u 资料片：%u）' WHERE `entry` = 1142;
UPDATE `mangos_string` SET `content_loc4` = '由事件 %u（%s）刷新' WHERE `entry` = 1143;
UPDATE `mangos_string` SET `content_loc4` = '由事件 %u（%s）移除' WHERE `entry` = 1144;
UPDATE `mangos_string` SET `content_loc4` = '属于卡池 %u' WHERE `entry` = 1145;
UPDATE `mangos_string` SET `content_loc4` = '属于卡池 %u，顶层卡池 %u' WHERE `entry` = 1146;
UPDATE `mangos_string` SET `content_loc4` = '（顶层）卡池 %u 由事件 %u（%s）刷新' WHERE `entry` = 1147;
UPDATE `mangos_string` SET `content_loc4` = '（顶层）卡池 %u 由事件 %u（%s）移除' WHERE `entry` = 1148;
UPDATE `mangos_string` SET `content_loc4` = '（卡池 %u）' WHERE `entry` = 1149;
UPDATE `mangos_string` SET `content_loc4` = '（事件 %i）' WHERE `entry` = 1150;
UPDATE `mangos_string` SET `content_loc4` = '（卡池 %u 事件 %i）' WHERE `entry` = 1151;
UPDATE `mangos_string` SET `content_loc4` = '[可使用]' WHERE `entry` = 1152;
UPDATE `mangos_string` SET `content_loc4` = '获取 %s 的位串值：[字段]：%u [值]：%s' WHERE `entry` = 1153;
UPDATE `mangos_string` SET `content_loc4` = '%s 的位串值：[字段]：%u [值]：%s' WHERE `entry` = 1154;
UPDATE `mangos_string` SET `content_loc4` = '获取 %s 的十六进制值：[字段]：%u [值]：%x' WHERE `entry` = 1155;
UPDATE `mangos_string` SET `content_loc4` = '%s 的十六进制值：[字段]：%u [值]：%x' WHERE `entry` = 1156;
UPDATE `mangos_string` SET `content_loc4` = '将 %s 的十六进制字段 %u %s %x = %x（十六进制）' WHERE `entry` = 1157;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的十六进制字段 %u %s %x = %x（十六进制）' WHERE `entry` = 1158;
UPDATE `mangos_string` SET `content_loc4` = '将 %s 的 float 字段 %u 加上：%f = %f' WHERE `entry` = 1159;
UPDATE `mangos_string` SET `content_loc4` = '你将 %s 的 float 字段 %u 加上：%f = %f' WHERE `entry` = 1160;
UPDATE `mangos_string` SET `content_loc4` = '法术 %u 没有光环。' WHERE `entry` = 1165;
UPDATE `mangos_string` SET `content_loc4` = '未找到脚本库或无法访问。' WHERE `entry` = 1166;
UPDATE `mangos_string` SET `content_loc4` = '脚本库的列表函数有误（版本过旧？）。' WHERE `entry` = 1167;
UPDATE `mangos_string` SET `content_loc4` = '脚本库已重载。' WHERE `entry` = 1168;
UPDATE `mangos_string` SET `content_loc4` = '脚本库是为不同版本的 mangosd 构建的。' WHERE `entry` = 1169;
UPDATE `mangos_string` SET `content_loc4` = '账号 %s（id %u）的锁定字段已改为 %u。' WHERE `entry` = 1170;
UPDATE `mangos_string` SET `content_loc4` = '参数错误。用法：\n.account set locked <账号名> <数值>\n锁定类型：0 无，1 IP，2 PIN，4 动态密码，8 强制' WHERE `entry` = 1171;
UPDATE `mangos_string` SET `content_loc4` = '骑术类型无效。请尝试以下之一：\n%s' WHERE `entry` = 1172;
UPDATE `mangos_string` SET `content_loc4` = '该玩家没有 %s 骑术技能。' WHERE `entry` = 1173;
UPDATE `mangos_string` SET `content_loc4` = '尝试移除骑术技能时出错。' WHERE `entry` = 1174;
UPDATE `mangos_string` SET `content_loc4` = '已从玩家 %s 移除骑术技能。' WHERE `entry` = 1175;
UPDATE `mangos_string` SET `content_loc4` = '模型 %d - |cffffffff|Hcreature_model_entry:%d|h[%s]|h|r ' WHERE `entry` = 1176;
UPDATE `mangos_string` SET `content_loc4` = '未找到生物模型！' WHERE `entry` = 1177;
UPDATE `mangos_string` SET `content_loc4` = '你尝试观看过场动画 %u，但它不存在。' WHERE `entry` = 1200;
UPDATE `mangos_string` SET `content_loc4` = '法术 %u %s = %f（*1.88 = %f）数据库 = %f 攻击强度 = %f' WHERE `entry` = 1202;
UPDATE `mangos_string` SET `content_loc4` = '直接治疗' WHERE `entry` = 1203;
UPDATE `mangos_string` SET `content_loc4` = '直接伤害' WHERE `entry` = 1204;
UPDATE `mangos_string` SET `content_loc4` = '持续治疗' WHERE `entry` = 1205;
UPDATE `mangos_string` SET `content_loc4` = '持续伤害' WHERE `entry` = 1206;
UPDATE `mangos_string` SET `content_loc4` = '%u - [%s] 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u 几率：%f %s' WHERE `entry` = 1500;
UPDATE `mangos_string` SET `content_loc4` = '%u - |cffffffff|Hpool:%u|h[%s]|h|r 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u %s' WHERE `entry` = 1501;
UPDATE `mangos_string` SET `content_loc4` = '%u - [%s] 自动刷新：%u 上限：%u 生物：%u 物件：%u 卡池 %u %s' WHERE `entry` = 1502;
UPDATE `mangos_string` SET `content_loc4` = '无法添加刷新点，因为预留 guid 范围内没有可用于静态刷新的 guid。使用该命令前需重启服务器。另请查看 GuidReserveSize.* 配置项。' WHERE `entry` = 1503;
UPDATE `mangos_string` SET `content_loc4` = 'NPC 编号 %u 的 AI 信息' WHERE `entry` = 1504;
UPDATE `mangos_string` SET `content_loc4` = 'AI 名称：%s（%s）脚本名：%s' WHERE `entry` = 1505;
UPDATE `mangos_string` SET `content_loc4` = '当前阶段 = %u' WHERE `entry` = 1506;
UPDATE `mangos_string` SET `content_loc4` = '战斗移动已 %s' WHERE `entry` = 1507;
UPDATE `mangos_string` SET `content_loc4` = '近战攻击已 %s' WHERE `entry` = 1508;
UPDATE `mangos_string` SET `content_loc4` = '移动类型 = %s（%u）' WHERE `entry` = 1509;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 已禁用！' WHERE `entry` = 1600;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 已经启用！' WHERE `entry` = 1601;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 已启用！' WHERE `entry` = 1602;
UPDATE `mangos_string` SET `content_loc4` = '事件 %u 已经禁用！' WHERE `entry` = 1603;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00角色|r|cffff00ff %s |r|cff00ff00放弃了他的工单。工单编号：|r|cffff00ff %d。|r' WHERE `entry` = 2002;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00关闭者|r：|cff00ccff %s|r ' WHERE `entry` = 2003;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00删除者|r：|cff00ccff %s|r ' WHERE `entry` = 2004;
UPDATE `mangos_string` SET `content_loc4` = '未找到工单。' WHERE `entry` = 2005;
UPDATE `mangos_string` SET `content_loc4` = '永久删除工单前请先关闭它。' WHERE `entry` = 2006;
UPDATE `mangos_string` SET `content_loc4` = '工单 %d 已被指派。' WHERE `entry` = 2007;
UPDATE `mangos_string` SET `content_loc4` = '已从数据库成功重载 %u 个工单。' WHERE `entry` = 2008;
UPDATE `mangos_string` SET `content_loc4` = '显示未关闭工单列表。' WHERE `entry` = 2009;
UPDATE `mangos_string` SET `content_loc4` = '显示创建者当前在线的未关闭工单列表。' WHERE `entry` = 2010;
UPDATE `mangos_string` SET `content_loc4` = '显示已关闭工单列表。' WHERE `entry` = 2011;
UPDATE `mangos_string` SET `content_loc4` = '指定的名称无效。名称应为在线管理员的名称。' WHERE `entry` = 2012;
UPDATE `mangos_string` SET `content_loc4` = '该工单已指派给你自己。要取消指派请使用 .ticket unassign %d，然后重新指派。' WHERE `entry` = 2013;
UPDATE `mangos_string` SET `content_loc4` = '工单 %d 未被指派，无法取消指派。' WHERE `entry` = 2014;
UPDATE `mangos_string` SET `content_loc4` = '你无法取消安全等级比你高的成员的工单指派。' WHERE `entry` = 2015;
UPDATE `mangos_string` SET `content_loc4` = '无法关闭工单 %d，它已被指派给另一位管理员。' WHERE `entry` = 2016;
UPDATE `mangos_string` SET `content_loc4` = '|cffaaffaa工单|r：|cffaaccff %d。|r ' WHERE `entry` = 2017;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00创建者|r：|cff00ccff %s|r ' WHERE `entry` = 2018;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00变更于|r：|cff00ccff %s 前|r ' WHERE `entry` = 2019;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00指派给|r：|cff00ccff %s|r ' WHERE `entry` = 2020;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00取消指派者|r：|cff00ccff %s|r ' WHERE `entry` = 2021;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00工单内容|r: [%s]|r' WHERE `entry` = 2022;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00管理员备注|r: [%s]|r' WHERE `entry` = 2023;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ccff%s|r |cff00ff00添加了备注|r: [%s]|r' WHERE `entry` = 2024;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00创建于|r：|cff00ccff %s 前|r ' WHERE `entry` = 2025;
UPDATE `mangos_string` SET `content_loc4` = '已升级列表中的工单：' WHERE `entry` = 2026;
UPDATE `mangos_string` SET `content_loc4` = '仍有待处理的未关闭工单，请先关闭它们！' WHERE `entry` = 2027;
UPDATE `mangos_string` SET `content_loc4` = '所有已关闭工单已删除，计数器重置为 |cffff00ff 1|r' WHERE `entry` = 2028;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00工单回复|r: [%s]|r' WHERE `entry` = 2029;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00完成者|r：|cff00ccff %s|r ' WHERE `entry` = 2030;
UPDATE `mangos_string` SET `content_loc4` = '工单功能现已禁用' WHERE `entry` = 2031;
UPDATE `mangos_string` SET `content_loc4` = '工单功能现已开放' WHERE `entry` = 2040;
UPDATE `mangos_string` SET `content_loc4` = '工单功能现已禁用' WHERE `entry` = 2041;
UPDATE `mangos_string` SET `content_loc4` = '工单 %s 的回复已重置。' WHERE `entry` = 2042;
UPDATE `mangos_string` SET `content_loc4` = '该工单已归档（已完成或已关闭）。' WHERE `entry` = 2043;
UPDATE `mangos_string` SET `content_loc4` = '该工单已被指派给某人。请先取消指派。' WHERE `entry` = 2044;
UPDATE `mangos_string` SET `content_loc4` = '工单 #%u 已加入升级列表。' WHERE `entry` = 2045;
UPDATE `mangos_string` SET `content_loc4` = '%s：等级 %u' WHERE `entry` = 2046;
UPDATE `mangos_string` SET `content_loc4` = '该工单已经完成了。请新建一个工单。' WHERE `entry` = 2047;
UPDATE `mangos_string` SET `content_loc4` = '你的工单已被编辑并附加回复。' WHERE `entry` = 2048;
UPDATE `mangos_string` SET `content_loc4` = '管理员工单计数器已设为工单 #%u' WHERE `entry` = 2051;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00新工单来自|r|cffff00ff %s。|r |cff00ff00分类：|r|cffff00ff %s。|r |cff00ff00工单编号：|r|cffff00ff %d。|r' WHERE `entry` = 2052;
UPDATE `mangos_string` SET `content_loc4` = '|cff00ff00角色|r|cffff00ff %s |r|cff00ff00编辑了他的工单。工单编号：|r|cffff00ff %d。|r' WHERE `entry` = 2053;
UPDATE `mangos_string` SET `content_loc4` = '%u - |c00f00fff*|r|cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u' WHERE `entry` = 11001;
UPDATE `mangos_string` SET `content_loc4` = '链接 ID：%u' WHERE `entry` = 11010;
UPDATE `mangos_string` SET `content_loc4` = '法力值（基础）：%u。（最大）：%u。（当前）：%u。' WHERE `entry` = 11017;
UPDATE `mangos_string` SET `content_loc4` = '开' WHERE `entry` = 38;
UPDATE `mangos_string` SET `content_loc4` = '否' WHERE `entry` = 422;

